### ISSUE TITLE
When linking 3+ datasets, all records that match against the master source should have same z_cluster

### ISSUE THREAD

**Issue by danieldynasty** [zinggAI/zingg#108]
All records that match against the master source should have same z_cluster. The output is currently in pairs.

**Comment by sonalgoyal** [comment]
Thanks for reporting this, it makes sense to align the output with same z_cluster from the master source. Will fix!

**Comment by navinrathore** [comment]
For Linking phase only, cluster id could be comprised of z_id. In this case, z_id of source[0]. Thereafter, all the related records will automatically have unique cluster_id.

Else, set of records with same z_id shall be given some other unique identifier.
