### ISSUE TITLE
More example models

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#110]
Relevant data here:
https://github.com/anhaidgroup/deepmatcher/blob/master/Datasets.md
http://pages.cs.wisc.edu/~anhai/data1/deepmatcher_data/Structured.zip

_Originally posted by @mliscombe in https://github.com/zinggAI/zingg/issues/95#issuecomment-1005369119_

**Comment by navinrathore** [comment]
To work with next 2 datasets namely
1. BeerAdvo-RateBeer
2. iTunes-Amazon1
