### ISSUE TITLE
Labeller - if it is not known that it is a match or not, similarity score should not be printed

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#114]
Current Message:
Zingg predicts the above records ARE NOT KNOWN IF MATCH with a similarity score of 0.00

New Message(only if not known)
Zingg does not any prediction for the above pairs as Zingg is still collecting training data to build the preliminary models.

**Comment by navinrathore** [comment]
Please elaborate bit more on the scenario.
working with febrl data, I haven't found above case. all are either MATCH or NON MATCH (zingg prediction)

**Comment by sonalgoyal** [comment]
The first time we run findTrainingData and label, them labelled prints this

**Comment by navinrathore** [comment]
if prediciton is IS_NOT_KNOWN_PREDICTION, the new message should be printed.

**Comment by sonalgoyal** [comment]
yes, thats probably one way of looking at it.
