### ISSUE TITLE
Umlaut or similar ("ä, ö, ü ...") characters cannot be displayed correctly in the console.

### ISSUE THREAD

**Issue by delgermurun** [zinggAI/zingg#116]
When I'm labeling, Zingg is unable to show me *ä, ö, ü ...* kinds of characters correctly in the console. The console shows *?* instead of the correct character.

File's encoding is `utf-8` and CSV file.

 - OS: macOS Monterey. But I am running Zingg from Docker.
 - iTerm2 with `zsh`.
 - Zingg version `0.3.1`

Thank you in advance!

**Comment by sonalgoyal** [comment]
@navinrathore - can you please take a look at this? you can replace our febrl test file with some of the above characters and test.

**Comment by navinrathore** [comment]
I quickly checked by running zingg on a xterm (Ubuntu-20). These chars were display on screen. On your iterm2, Could you try to run cat <filename> and let us know if it shows these chars or not?
![image](https://user-images.githubusercontent.com/19220734/148538989-58a0caf5-2245-4d1c-8927-433704876fcd.png)

**Comment by sonalgoyal** [comment]
@delgermurun - can you please check?

**Comment by delgermurun** [comment]
@navinrathore @sonalgoyal thanks for the quick responses.

`cat <filename>` works fine on my iTerm2.
![image](https://user-images.githubusercontent.com/492616/148552415-8de825b7-8442-4d4c-9170-1666b78624eb.png)

**Comment by sonalgoyal** [comment]
which version of java are you using @delgermurun ?

**Comment by delgermurun** [comment]
@sonalgoyal I am running Zingg's Docker image directly (by binding my data directory as a volume)
here is an output of the `java -version` command.

```sh
I have no name!@0bf5a68b729f:/zingg-0.3.1-SNAPSHOT/scripts$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

**Comment by sonalgoyal** [comment]
hmm..does cat file work fine in the docker?

**Comment by delgermurun** [comment]
just checked. Yes `cat` works fine in the docker.

**Comment by navinrathore** [comment]
@delgermurun Please test with febrl data also once. Add a few sample strings in test.csv (examples/febrl folder) and run findTrainingData and label. You may give new model no.
This will help us narrow down the issue.

**Comment by sonalgoyal** [comment]
@delgermurun let us run a few tests to narrow down this problem.
- update test.csv in examples/ febrl with the characters

**Comment by sonalgoyal** [comment]
@navinrathore have we tested the umlaut characters in docker?

**Comment by navinrathore** [comment]
Yes. It is reproducible in Docker image.
@delgermurun, we will work on it. Thanks.

**Comment by navinrathore** [comment]
@delgermurun , Please set the below environment variable for locale. Umlauts will be displayed on screen while Labeling. 

export LANG=C.UTF-8

They are fine in Match output. It is just an issue related to display.

**Comment by sonalgoyal** [comment]
That’s a good find @navinrathore, can we set this in the docker file for the future as well?

**Comment by navinrathore** [comment]
Current locale setting on Docker image is:
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"

Current locale availability
$ locale -av
locale: C.UTF-8         directory: /usr/lib/locale/C.UTF-8

we will fix this issue in docker image. Thanks.

**Comment by delgermurun** [comment]
I can confirm that `export LANG=C.UTF-8` works!

Thanks.

**Comment by sonalgoyal** [comment]
Awesome @delgermurun , thanks @navinrathore for the quick turnaround!
