### ISSUE TITLE
The link is broken https://docs.zingg.ai/docs/analytics.html

### ISSUE THREAD

**Issue by navinrathore** [zinggAI/zingg#129]
The link to Analytics page in banner is broken.
Broken Link: https://docs.zingg.ai/docs/analytics.html

**Comment by navinrathore** [comment]
It should refer to https://docs.zingg.ai/docs/security.html where the related content is present.

**Comment by sonalgoyal** [comment]
607f095129c790cf407dd6ff68f2712252a26ade
