### ISSUE TITLE
Assign a custom z_cluster id to the master source dataset for link phase

### ISSUE THREAD

**Issue by delta824** [zinggAI/zingg#132]
Problem: The z_cluster value is changing after each training / model re-build.
Proposed solution: The user can assign a custom z_cluster value/id in the master dataset for the link phase to use so all other datasets will inherit the custom z_cluster id in the output.

**Comment by sonalgoyal** [comment]
the link phase does take the cluster id of the master(first dataset). Is that not what you see? Can you please post an example and the steps you performed where this breaks? @delta824
