### ISSUE TITLE
Snowpark support

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#138]
It will be nice to have a native Snowflake version of Zingg which can run without Spark. While looking at snowpark, here are the first level thoughts
- Need to figure out the Java/Scala integration as Snowpark is in Scala. should be doable but some changes may need conversions etc
- Snowpark doesnt have Graphframes and MLLib equivalents
- The Dataset API looks similar but there may be gaps
- the pipe abstraction will no longer be needed, as we will assume data is in Snowflake
- The interactive learner needs to be thought through. Where will its interface lie? 
- Spark Context etc classes need to change

Our approach could be 
- adapter pattern
- parameterization of classes for both types
- new code base(NO!!!)
- some other

I will try and form an opinion on this after checking one flow (findtrainingData?) and see what needs to be done to make it Snowpark compatible. Will jot down findings here.

**Comment by navinrathore** [comment]
Initial java and scala files to test basics of Snowpark
[MainTest.java.txt](https://github.com/zinggAI/zingg/files/8045788/MainTest.java.txt)
[Main.scala.txt](https://github.com/zinggAI/zingg/files/8045789/Main.scala.txt)

**Comment by nipunj15** [comment]
Hey @sonalgoyal @navinrathore, looking forward to using Zingg natively on top of Snowflake. Any timelines you have in mind for this feature?

**Comment by sonalgoyal** [comment]
that is great to hear @nipunj15. Sorry we do not have a timeline yet

**Comment by sonalgoyal** [comment]
Snowflake is now natively supported in Zingg enterprise
