### ISSUE TITLE
Add user to docker command

### ISSUE THREAD

**Issue by jdicello** [zinggAI/zingg#159]
**Describe the bug**
The current docker command does not specify a user.  When the container is run w/o a user, you are unable to modify the file system. The instructions ask you to rename a directory, but that command will fail.  Additionally, VS Code requires the ability to create directories to connect to a running container.

**To Reproduce**
1. Run the commands:
docker pull zingg/zingg:0.3.2
docker run -it zingg/zingg:0.3.2 bash
3. When the session has started, type the command "mkdir test_dir"
![image](https://user-images.githubusercontent.com/2998073/156631610-e46005a4-93a7-40c8-affb-c2a8f8a41643.png)

**Expected behavior**
The directory "test_dir" should be created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WSL2 - Ubuntu

**Smartphone (please complete the following information):**

**Additional context**
I was able to fix the problem by adding "-u root" to the docker command.  I am not sure if this is the ideal way to give this permission.

**Comment by sonalgoyal** [comment]
Thanks for reporting this @jdicello. we will try to fix this as soon as possible. @navinrathore can you please take a look at this urgently? Thanks.

**Comment by sonalgoyal** [comment]
Added docker instructions https://docs.zingg.ai/zingg/stepbystep/installation/workingwithdocker. Hope this helps @jdicello

**Comment by sonalgoyal** [comment]
Confirmed with @jdicello and closing
