### ISSUE TITLE
Support nested json data sources.

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#168]
**Is your feature request related to a problem? Please describe.**
When feeding Zingg ndjson that has depth, such as an array or an object, Zingg flattens the record, discarding, the objects name. This is an information loss, exposes potential  name conflicts, and requires different field definitions findTrainingData and label phases.

**Describe the solution you'd like**
Recursively identify the nested objects and include the object names as prefixes to that attribute names. I prefer dot notation, but I imagine underscores might be more popular.

**Comment by sonalgoyal** [comment]
@navinrathore please check how we can support nested json or parquet

**Comment by sonalgoyal** [comment]
We dont have many users reporting ndjson usage. Not fixing
