### ISSUE TITLE
cleaner labeling ux

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#169]
**Is your feature request related to a problem? Please describe.**
In the labeling phase only show the fields included in matching. For example, in this config, only `name` and `address` are being used, but the table when labeling, includes all the fields making the terminal a bit unwieldy.
![image](https://user-images.githubusercontent.com/50412/157386021-a4d47743-635e-4380-93ef-dbba595bb1c9.png)

**Describe the solution you'd like**
Only show the fields used in matching for labeling output.

**Comment by sonalgoyal** [comment]
Thanks for reporting this issue @tomdavidson. We show the fields that are configured in fieldDefinitions as they are generally meaningful to the labeling. Say fields which could be not that well populated but when present can be useful to say if they are matches. Does that make sense?

Do you think having a vertical view would help you in this case? would you find it more readable?

**Comment by sonalgoyal** [comment]
let us have a flag --showConcise and then only show the fields which are not DONT_USE. The change will only be in display, not in any saving the training datasete etc.

**Comment by tomdavidson** [comment]
Ah I see, the fields might not be used in the ML model but used by us humans in training the model.

In this particular case, those other fields do not inform the training at all, but wanted to keep the data rather than separating and rejoining later. Perhaps that is no the typical practice.

The --showConcise might provide a better UX. Maybe there is another type that is pass through and never shown (what I though DONT_USE was) and a type used for interactive training? Im not sure, but I think UX is quite important when used as a CLI rather than a lib.

**Comment by sonalgoyal** [comment]
agree UX is critical. Let us build the flag --showConcise @navinrathore as discussed here with @tomdavidson
