### ISSUE TITLE
labeling feedback loop from usage

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#184]
**Is your feature request related to a problem? Please describe.**

The clustering is not 100% perfect... we need a learning loop to capture the edge cases for additional training. 

**Describe the solution you'd like**

I think storing ML metadata such, as labels, in human readable format could present opportunities. When the edge case comes up, a label could be manually added via pull request.

**Describe alternatives you've considered**

Perhaps a CLI option to import manual labels would be nice. Then if the data was in a db instead of git, the DX would be the same.

**Comment by sonalgoyal** [comment]
Thank you for requesting this feature. Have you checked https://docs.zingg.ai/zingg/stepbystep/createtrainingdata/addowntrainingdata by which you can add labeled data to the model and https://docs.zingg.ai/zingg/generatingdocumentation ?

We currently save the metadata under models/id/trainingData folder in parquet format. The generateDocs provided above writes the data in html format. The https://docs.zingg.ai/zingg/stepbystep/createtrainingdata/exportlabeleddata outlines how you can conver the training data to csv for further import. 

Eventually we want to support the workflow that you have outlined. Let me know what else you would need to support your workflow?

**Comment by sonalgoyal** [comment]
this is interesting feedback. please feel free to add an issue for that.
