### ISSUE TITLE
Reported by Tom in Slack: match output is different with different output formats (parquet and json).

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#185]
More details at https://zinggai.slack.com/archives/C02JNH144TB/p1647996922060069

**Comment by navinrathore** [comment]
The tests were run with the given config and input data. For both parquet and json output types, the field data/statistics are exactly same. Verification of results are captured in the following file. Pyspark shell has been used. user supplied output files of different types are also exactly same.

[comparision.txt](https://github.com/zinggAI/zingg/files/8338508/comparision.txt)

There was conclusion that data visualization tool was handling parquet files erroneously.

**Comment by sonalgoyal** [comment]
confirmed with user, not a bug.
