### ISSUE TITLE
issue on running the zingg_0.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by premsmac2021** [zinggAI/zingg#193]
22/03/31 12:18:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/03/31 12:18:00 WARN DependencyUtils: Local jar /Users/prem/zingg/zingg/zingg-0.3.0-SNAPSHOT.jar does not exist, skipping.
Error: Failed to load class zingg.client.Client.
22/03/31 12:18:00 INFO ShutdownHookManager: Shutdown hook called
22/03/31 12:18:00 INFO ShutdownHookManager: Deleting directory /private/var/folders/h4/my7c_q2j733106q4jjdwnbfm0000gn/T/spark-77590a74-3d55-4b1c-81a8-3797f15830ff

**Comment by navinrathore** [comment]
ZINGG_HOME should point to the newly built jar file from the source code. the line no. 2. in scripts/zingg.sh should be uncommented.
#ZINGG_HOME=./assembly/target

**Comment by sonalgoyal** [comment]
what happens if we set zINGG_HOME to the location of the jar but do not uncomment? If it does not work, let us fix and push a new release out

**Comment by navinrathore** [comment]
The reason behind this error message is Zingg jar is not reachable. 
Possible reasons are:
a) ZINGG_HOME is not pointing to correct location of the jar file.
b) startup skill zingg.sh referring to old jar file. It is possible that user upgraded to just the Zingg jar file but not the other files of the release.

**Comment by premsmac2021** [comment]
It's working now (version 0.3.2)
