### ISSUE TITLE
hamcrest in pom?

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#198]
Check why we have hamcrest in the pom. I dont remember using it.

**Comment by navinrathore** [comment]
hamcrest is a framework that supports declarative rules for Matching. It is commonly used to write flexible tests. To get declarative assert output for unit test failures, it is used in Zingg.
Its scope is limited to "Test".

**Comment by sonalgoyal** [comment]
leaving it in there for junits
