### ISSUE TITLE
how to config the fieldDefinition section for 2 sources with different schemas?

### ISSUE THREAD

**Issue by lsbilbro** [zinggAI/zingg#204]
Hi Sonal!

Was just noticing in your examples that match 2 data sources together, they always have the same input schema.
How would the fieldDefinition config section change if, for example, your input data sources had different columns names?

e.g.

source1:  FName, LName, Addr
source2: First, Last, Address

**Comment by sonalgoyal** [comment]
Hi Luke!

this is something we are planning to build through the fieldname and fields properties in the config. Currently, Zingg expects the same column names. if this is a blocker, please let me know and we will prioritize.

**Comment by lsbilbro** [comment]
Not a blocker... but good to know you are thinking about it!
