### ISSUE TITLE
zingg-0.3.0-SNAPSHOT.jar is not available

### ISSUE THREAD

**Issue by piyushank** [zinggAI/zingg#22]
I have tried to run Zingg utility as per steps shown in readme but zingg-0.3.0-SNAPSHOT.jar referred in zingg.sh is not present in published code. Kindly provide the same

**Comment by sonalgoyal** [comment]
Thanks for trying Zingg out @piyushank ! Looks like there was a problem with the tar, uploaded it at https://github.com/zinggAI/zingg/releases/tag/v0.3.0. Please try the snapshot tar.gz or the zip and let me know if you have any troubles. Good luck!
