### ISSUE TITLE
configuration should be used for generateDocs phase?

### ISSUE THREAD

**Issue by lsbilbro** [zinggAI/zingg#220]
What configuration should we use for generateDocs?

I tried the one I use for findTrainingData but ended up getting an error (stderr attached):
`java.io.FileNotFoundException: /home/lucas.bilbro@databricks.com/NCVoter360/zinggModels/April19_voters/model.html (No such file or directory)`

I'm suspect the is that this job is not compatible with Databricks yet... but wanted to double check.
To be clear, this is not a major blocker... just a question 😃 

[stderr.txt](https://github.com/zinggAI/zingg/files/8547329/stderr.txt)

**Comment by sonalgoyal** [comment]
hi Luke,

Yes, you are right. the generateDocs and updateLabels are both not ported
to Databricks yet. Let us leave this question open so that we can fix.

Cheers,
Sonal
https://github.com/zinggAI/zingg

**Comment by sonalgoyal** [comment]
fixed in 0.4.0
