### ISSUE TITLE
numPartitions guidance?

### ISSUE THREAD

**Issue by lsbilbro** [zinggAI/zingg#221]
In the doc you recommend setting numPartitions to ~20-30x the number of worker cores.

Is that a good rule of thumb for all job types? (e.g. findTrainingData, trainMatch, link, etc)

**Comment by sonalgoyal** [comment]
yes, all the jobs use this to partition the blocked/indexed records. there
is one aspect of findTrainingData which we have not been able to
parallelize on Spark, but there are other aspects of the phase that use
this.
Cheers,
Sonal
https://github.com/zinggAI/zingg
