### ISSUE TITLE
Reuse lables for differnt models?

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#224]
**Describe the question**
I am experimenting matching on different fields and with different prep, but my labels are the same.

Do the labels need to match the same fields used in the training or can it just be the z_cluster, z_isMatch, and a record id such as a uuid?

**Comment by sonalgoyal** [comment]
Yes the labels need to match the training fields as we need to learn on them. Many users don’t seem to have a uid so we kept it like this

**Comment by tomdavidson** [comment]
Thanks
