### ISSUE TITLE
matching against empty fields and our of order fields

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#225]
**Describe the question**
Some of my entities have po boxes, some have street addresses, some have both. Im trying to understand the inner-workings so I can use the tool smarter and rely less on magic.

How does Zingg use a po box from record A when record B does not have one? The edit distance would be large right?

Second scenario, I can combine the po box string and the street address string and match on the combined string, but again, some records will not have one or the other. What does Zingg do in this case? Do I need to always make sure the po box is first?

**Comment by sonalgoyal** [comment]
For every match type, Zingg computes one or many similarity distances. Here are the features configured currently. https://github.com/zinggAI/zingg/blob/main/core/src/main/java/zingg/feature/StringFeature.java 
We do a polynomial expansion of the features and feed them to a logistic regression classifier

currently nulls are handled as matches. We have an ongoing issue #91 where we will distinguish nulls. 

In your case, a new field with concatenated data could work, you can code a custom similarity function that handles the ma thing for that particular field. In fact, we are planning to open up the ability to define these functions #37 

Here is the documentation for the functions, need to add more stuff but hope it helps
https://docs.zingg.ai/zingg/improving-accuracy/definingown
