### ISSUE TITLE
config | field deffinitions | alphanumeric

### ISSUE THREAD

**Issue by tomdavidson** [zinggAI/zingg#232]
**Describe the question**
The docs describe three match types:

- FUZZY
- EXACT
- DONT USE

There is at least one other not included in the docs:

- ALPHANUMERIC

ALPHANUMERIC matches numbers in strings. Does the rest of the string get matched (EXACT or FUZZY)? Should it always be used when there are meaningful numbers such as address parts or post codes?

**Comment by sonalgoyal** [comment]
Addressed through the new features exposed, for eg IS_NULL_OR_EMPTY etc. Documentation coming as part of 0.3.4 release.
