### ISSUE TITLE
Client argument list formatting

### ISSUE THREAD

**Issue by lsbilbro** [zinggAI/zingg#24]
**Describe the bug**
Hello!  I'm testing this out on Azure Databricks.  I believe my job spec is correct:

```
{
    "settings": {
        "new_cluster": {
            "spark_version": "7.3.x-scala2.12",
            "spark_conf": {
                "spark.databricks.delta.preview.enabled": "true"
            },
            "azure_attributes": {
                "availability": "ON_DEMAND_AZURE",
                "first_on_demand": 1,
                "spot_bid_max_price": -1
            },
            "node_type_id": "Standard_DS3_v2",
            "enable_elastic_disk": true,
            "num_workers": 5
        },
        "libraries": [
            {
                "jar": "dbfs:/FileStore/jars/960f43e3_3c55_4c5b_a296_e69bc80ed1a6-zingg_0_3_0_SNAPSHOT-aa6ea.jar"
            },
            {
                "maven": {
                    "coordinates": "org.jsoup:jsoup:1.7.2"
                }
            }
        ],
        "spark_jar_task": {
            "main_class_name": "zingg.client.Client",
            "parameters": [
                "--phase",
                "findTrainingData",
                "--conf",
                "dbfs:/Bilbro/examples/zinggconfig.json"
            ],
            "run_as_repl": true
        },
        "email_notifications": {},
        "name": "zinggtest",
        "max_concurrent_runs": 1
    }
}
```

But the main class does not appear to accept a list of strings.  I receive this error:
```
21/09/22 20:41:51 command--1:1: error: type mismatch;
 found   : Array[String]
 required: String
zingg.client.Client.main(Array("--phase","findTrainingData","--conf","dbfs:/Bilbro/examples/zinggconfig.json"))
                              ^
```

**Comment by sonalgoyal** [comment]
Thanks for trying Zingg @lsbilbro ! Are you using the create job and then the run-now? https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/jobs#run-now or are you using the runs-submit endpoint? https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/jobs#jobsjobsservicesubmitrun

**Comment by lsbilbro** [comment]
I'm using the Jobs UI "run now" button, which is hitting an internal endpoint but should be closest to the run-now public endpoint.

**Comment by mspencer92** [comment]
I am also having this same problem, how do we fix this?

**Comment by sonalgoyal** [comment]
Are you also on Azure @mspencer92 ?

**Comment by mspencer92** [comment]
@sonalgoyal I am

**Comment by sonalgoyal** [comment]
Thanks @mspencer92 and @lsbilbro , let me try a few options and get back. In the meantime, can you try making the parameters as a string ("parameters" :"--phase findTrainingData......") and see if that works?

**Comment by mspencer92** [comment]
@sonalgoyal Same issue ```21/09/23 17:27:02 command--1:1: error: type mismatch;
 found   : Array[String]
 required: String
zingg.client.Client.main(Array("--phase findTrainingData --conf dbfs:/config.json"))```

**Comment by sonalgoyal** [comment]
can you please post the json @mspencer92 ?

**Comment by mspencer92** [comment]
```{
    "settings": {
        "new_cluster": {
            "spark_version": "7.3.x-scala2.12",
            "spark_conf": {
                "spark.databricks.delta.preview.enabled": "true"
            },
            "azure_attributes": {
                "availability": "ON_DEMAND_AZURE"
            },
            "node_type_id": "Standard_DS4_v2",
            "enable_elastic_disk": true,
            "num_workers": 5
        },
        "libraries": [
            {
                "maven": {
                    "coordinates": "org.jsoup:jsoup:1.7.2"
                }
            },
            {
                "jar": "dbfs:/FileStore/jars/6e9ca9cb_d964_4fb1_9d65_b71c36efbb40-zingg_0_3_0_SNAPSHOT-aa6ea.jar"
            }
        ],
        "spark_jar_task": {
            "main_class_name": "zingg.client.Client",
            "parameters": [
                "--phase findTrainingData --conf dbfs:/config.json"
            ],
            "run_as_repl": true
        },
        "timeout_seconds": 3600,
        "max_retries": 1,
        "email_notifications": {},
        "name": "Zingg",
        "max_concurrent_runs": 1
    }
}```

I created the job with the parameters as a string but Azure converted it back to an array...

**Comment by sonalgoyal** [comment]
is this the response then?

**Comment by mspencer92** [comment]
Yes

**Comment by sonalgoyal** [comment]
yeah you are right, both passing in an array or a string does not work. trying sparksubmitjob now!

**Comment by mspencer92** [comment]
@sonalgoyal Okay thank you.

**Comment by sonalgoyal** [comment]
sure @mspencer92 ! It's almost midnight here so I will take a look at it tomorrow morning and update this issue. Hope that works and sorry for the delay.

**Comment by sonalgoyal** [comment]
{
    "settings": {
        "new_cluster": {
            "spark_version": "7.3.x-scala2.12",
            "azure_attributes": {
                "availability": "ON_DEMAND_AZURE",
                "first_on_demand": 1,
                "spot_bid_max_price": -1
            },
            "node_type_id": "Standard_F4",
            "driver_node_type_id": "Standard_F4",
            "enable_elastic_disk": true
        },
        "spark_submit_task": {
            "parameters": [
                "--class",
                "zingg.client.Client",
                "dbfs:/FileStore/jars/114cd2d3_2e02_4eb6_96c6_aca9c9a0aa2c-zingg_0_3_0_SNAPSHOT-aa6ea.jar",
                "--phase=findTrainingData",
                "--conf=dbfs:/config.json",
                "--license=abc"
            ]
        },
        "email_notifications": {},
        "name": "ssZing1",
        "max_concurrent_runs": 1
    }
}

here is the json that worked for me. I had to put a dummy license in the end of the params too. @mspencer92 and @lsbilbro  please do try and let me know how it goes. good luck :-)

**Comment by sonalgoyal** [comment]
forgot to mention that I added the jar to azure workspace and used its location in the paramters. I believe dbfs should work too, but I havent had a chance to try that yet.

**Comment by mspencer92** [comment]
I will give it a try, thank you!

**Comment by sonalgoyal** [comment]
Also you have 5 workers set in the json you sent to me @mspencer92 . You may like to check the hardware sizing guide to assess how much hw you need.

**Comment by sonalgoyal** [comment]
please add these details to databricks documentation and close @navinrathore

**Comment by sonalgoyal** [comment]
closing this

**Comment by lsbilbro** [comment]
Hi Sonal,  Sorry for the delay in retesting this!

I set up a new job as per your suggestions:
```
{
    "settings": {
        "new_cluster": {
            "spark_version": "7.3.x-scala2.12",
            "spark_conf": {
                "spark.databricks.delta.preview.enabled": "true"
            },
            "azure_attributes": {
                "availability": "ON_DEMAND_AZURE"
            },
            "node_type_id": "Standard_F4",
            "driver_node_type_id": "Standard_F4",
            "enable_elastic_disk": true,
            "num_workers": 2
        },
        "spark_submit_task": {
            "parameters": [
                "--class",
                "zingg.client.Client",
                "dbfs:/Bilbro/code/zingg-0.3.0-SNAPSHOT.jar",
                "--phase=findTrainingData",
                "--conf=dbfs:/Bilbro/examples/zinggconfig.json",
                "--license=abc"
            ]
        },
        "email_notifications": {},
        "name": "ZinggTest3",
        "max_concurrent_runs": 1
    }
}
```

And the Driver logs do indicate the jar is being found:


```
21/12/14 16:34:47 INFO Utils: Fetching dbfs:/Bilbro/code/zingg-0.3.0-SNAPSHOT.jar to /local_disk0/tmp/spark-26df7bc7-e02e-4ef8-a142-842f447d5932/fetchFileTemp6622036023545350829.tmp
21/12/14 16:34:50 INFO Client: 
21/12/14 16:34:50 INFO Client: ********************************************************
21/12/14 16:34:50 INFO Client: *                    Zingg AI                           *
21/12/14 16:34:50 INFO Client: *               (C) 2021 Zingg.AI                       *
21/12/14 16:34:50 INFO Client: ********************************************************
21/12/14 16:34:50 INFO Client: 
21/12/14 16:34:50 INFO Client: using: Zingg v0.3
21/12/14 16:34:50 INFO Client: 
21/12/14 16:34:50 WARN Arguments: Config Argument is dbfs:/Bilbro/examples/zinggconfig.json
21/12/14 16:34:50 INFO ShutdownHookManager: Shutdown hook called
21/12/14 16:34:50 INFO ShutdownHookManager: Deleting directory /local_disk0/tmp/spark-26df7bc7-e02e-4ef8-a142-842f447d5932
```

But that's where things fail for me currently.
The config file cannot be found; the stderr reports:

```
java.io.FileNotFoundException: dbfs:/Bilbro/examples/zinggconfig.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:916)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at zingg.client.Arguments.createArgumentsFromJSON(Arguments.java:153)
	at zingg.client.Client.main(Client.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.NullPointerException
	at zingg.client.Client.main(Client.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

And this seems strange to me because the config file is definitely there:
```
(pybase) C02ZK18SLVDQ% databricks fs ls -l dbfs:/Bilbro/examples/zinggconfig.json
file  2188  zinggconfig.json  1639499291000
```

I'll attach the content of my config file to this entry , just in case (I had to change the extension to txt so the upload would work)
[zinggconfig.txt](https://github.com/zinggAI/zingg/files/7713383/zinggconfig.txt)
.

**Comment by sonalgoyal** [comment]
thanks for reporting this @lsbilbro ! I do remember running on Azure when you reported the issue earlier. Let me check what is going wrong. You are on Azure Databricks, right?

**Comment by sonalgoyal** [comment]
the thing that worked for me this time was not having dbfs as part of the config file name 
["--class","zingg.client.Client","dbfs:/FileStore/jars/e34dca2a_84a4_45fd_a9fd_fe0e1c7e283c-zingg_0_3_0_SNAPSHOT-aa6ea.jar","--phase=findTrainingData","--conf=/dbfs/FileStore/config.json","--license=abc"] 

The total JSON is

{
    "settings": {
        "new_cluster": {
            "spark_version": "7.3.x-scala2.12",
            "spark_conf": {
                "spark.databricks.cluster.profile": "singleNode",
                "spark.master": "local[*, 4]"
            },
            "aws_attributes": {
                "availability": "SPOT_WITH_FALLBACK",
                "first_on_demand": 1,
                "zone_id": "us-west-2a"
            },
            "node_type_id": "c5d.xlarge",
            "driver_node_type_id": "c5d.xlarge",
            "custom_tags": {
                "ResourceClass": "SingleNode"
            }
        },
        "spark_submit_task": {
            "parameters": [
                "--class",
                "zingg.client.Client",
                "dbfs:/FileStore/jars/e34dca2a_84a4_45fd_a9fd_fe0e1c7e283c-zingg_0_3_0_SNAPSHOT-aa6ea.jar",
                "--phase=findTrainingData",
                "--conf=/dbfs/FileStore/config.json",
                "--license=abc"
            ]
        },
        "email_notifications": {},
        "name": "test",
        "max_concurrent_runs": 1
    }
}


I still need to check how the interactive learner will work as it does System.out and that will break in the cloud env. Maybe we need to do a python based notebook for the cloud envs?

**Comment by sonalgoyal** [comment]
Opened issue #79.

**Comment by sonalgoyal** [comment]
verified through #79. docs are updated
