### ISSUE TITLE
Add new config files for "Amazon-google" dataset involving stop word removal.

### ISSUE THREAD

**Issue by navinrathore** [zinggAI/zingg#252]
**Description**
* For "Amazon-google" dataset, add new config with stopwords attributes
* Update documentation for, giving this example, how one can work with stop words.

**Comment by sonalgoyal** [comment]
It is not a new model, just add a new config and add documentation of first using config without stop words settings to generate, then select few files and edit them and put them in the main folder and create an updated config.
