### ISSUE TITLE
Run Zingg through PySpark

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#26]
Need to figure out how Zingg can be run from pyspark or python.

**Comment by jtinsky** [comment]
I start pyspark with these Delta extensions to use Delta tables and it works fine for me in the docker image you provided. 

`pyspark --packages io.delta:delta-core_2.12:0.8.0 \
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"`

**Comment by sonalgoyal** [comment]
thanks @jtinsky! yeah you are running Zingg by invoking spark-submit. I still need to figure out where and how people would like to use Zingg through PySpark. Keeping this open for further discussion as it is better to understand user requirements here.

**Comment by sonalgoyal** [comment]
duplicate of #243 , tracking there as we have more action happening on it.
