### ISSUE TITLE
more blocking functions for integer and double types

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#261]
We need to add more blocking functions for Integer and Double types other than the double and exact ones that we have

In all cases, handle 0 and Nan and negative numbers appropriately.
Both
- number without last digit. eg for integer type 234 and 233 will return 23, double type - 234.5 and 233.5 will return 23
- range functions. return 0 if num < 10, 1 if 10 < num < 100, 2 if less than 1000 but greater than 100, 3 if less than 10000(this can be odelled as FirstChars/LastChars functions, one base class and one derived class for each range)
- lessThan 0 function

extra functions for Double type
- number with one digit after decimal (23.4445 gives 23.44)
- number with 2 digits after decimal
- 3 digits after decimal
(both above to be modeled with one base class like firstchars)

**Comment by sonalgoyal** [comment]
please have appropriate junits for each - check the similarity function junits for an idea of how to build these junits.

**Comment by navinrathore** [comment]
Code changes made. Junits added.

**Comment by sonalgoyal** [comment]
i dont see the pr?
