### ISSUE TITLE
rename "dont use" to dont_use consistent with other match types

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#265]
our match tyes have underscores if they have multiple words. let us make "dont use" type consistent with this

**Comment by sonalgoyal** [comment]
also update documentation

**Comment by Bennykillua** [comment]
Where can I find the file? @sonalgoyal

**Comment by sonalgoyal** [comment]
MatchTypes.java is under client. Please do a complete search over the repo for all the mentions
