### ISSUE TITLE
test date type

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#278]
alter the febrl schema and change ssn to date type. make the match type fuzzy and see how it works.

**Comment by sonalgoyal** [comment]
@gnanaprakash-ravi can you check this?

**Comment by gnanaprakash-ravi** [comment]
code:
```
dob = FieldDefinition("dob", "date", MatchType.FUZZY)
schema = "id string, fname string, lname string, stNo string, add1 string, add2 string, city string, areacode string, state string, dob date, ssn  string"
```

with new model ID:
All 4 Python phases are working fine for date type in dob!!
