### ISSUE TITLE
error getting for trainMatch

### ISSUE THREAD

**Issue by sidharth16395** [zinggAI/zingg#287]
**Describe the question**
Please describe your question in detail. 
Hi sonal,
When i use below command:
 **zingg.sh --phase trainMatch --conf examples/configsid.json**
![image](https://user-images.githubusercontent.com/104770008/170192739-0c1d22d0-7833-4a18-b796-9cfce98e3b49.png)

**Comment by sonalgoyal** [comment]
how many matches and non matches do you have in your labelled data?

**Comment by sidharth16395** [comment]
Labelled pairs so far    : 1/41 MATCH, 40/41 DO NOT MATCH, 0/41 NOT SURE

Current labelling round  : 0/41 pairs labelled

**Comment by sonalgoyal** [comment]
to run train or trainMatch, you should have at least 30/40 matches in your labelled dataset. Please run findTrainingData/label till you have that and only then run train/trainMatch.

**Comment by sidharth16395** [comment]
yes sure let me try out.

**Comment by sonalgoyal** [comment]
fixed this in main branch for next release by e08a1b70268a7537480354424fcf34a886d0884a
