### ISSUE TITLE
Documenter should have model stats

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#299]
documenter should display number of total records, those marked as matches and non matches.

**Comment by sonalgoyal** [comment]
first run generateDocs on existing febrl model
then see which class is building the model documentation
we build a hashmap of vales. add the stats there
and then update the template.

**Comment by sonalgoyal** [comment]
Go to https://github.com/zinggAI/zingg/blob/ff81948dd2a490f43b4863aa79334beb7092eea7/core/src/main/java/zingg/documenter/ModelDocumenter.java#L65

create a new attribute unmarkedRecords - build like markedRecords.

update the hash with stats from marked and unmarkedRecords - size etc. 

edit the template

**Comment by sonalgoyal** [comment]
@vikasgupta78 please check this issue related to the documenter

**Comment by vikasgupta78** [comment]
fixed via commit 548c8384 , pull request #541
