### ISSUE TITLE
python api changes

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#322]
1. new pipes - snowflake, inmemory, bigquery, csv - default with header
2. client options is currently expecting an array [--phase","train"...] we need an empty constructor to which we can set phase. Also current constructor which takes in arguments is confusing, people will mistake it for Arguments object. let us rename
3. right now setData and setOutput have defaulted to one pipe. we will nto be able to do linking with two datatsets. need to do that.
4. do we really need zingg.init and zingg.execute? init is not doing much, maybe we can call it internally in execute?
5. location of zingg.py should be in api and not in phases

**Comment by navinrathore** [comment]
* Moved api in python/api folder
* Moved examples in python/examples folder
* same for scala specific files

**Comment by navinrathore** [comment]
In case, "module not found" error occurs, following variable could be set.
```
export PYTHONPATH=/home/navin/workDir/zingg-1/
```
