### ISSUE TITLE
labeller and update labeller

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#341]
decouple model from view so that we can expose the looping through the python api

**Comment by sonalgoyal** [comment]
@edmondo1984 would you like to restructure this code?

**Comment by edmondo1984** [comment]
@sonalgoyal can you provide the packages ?

**Comment by sonalgoyal** [comment]
@edmondo1984 - here is the labeller. https://github.com/zinggAI/zingg/blob/main/core/src/main/java/zingg/Labeller.java 
this is the class that brings up the interactive labeler which shows 0, 1 and 2 for the user to mark.  please let me know if you need further information.

**Comment by sonalgoyal** [comment]
@vikasgupta78 - ok to close this?

**Comment by vikasgupta78** [comment]
Pull request #583 should address this
