### ISSUE TITLE
python api changes

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#347]
add phase specific methods
inmemorypipe to accept pandas df

**Comment by sonalgoyal** [comment]
constants in pipes to move to java and referenced here

**Comment by sonalgoyal** [comment]
def getDfFromDs(self, data):
        return DataFrame(data, sqlContext) 

this gives an error /databricks/spark/python/pyspark/sql/dataframe.py:129: UserWarning: DataFrame constructor is internal. Do not directly use it.
  warnings.warn("DataFrame constructor is internal. Do not directly use it.")

**Comment by sonalgoyal** [comment]
getUnMarkedRecords - rename to getUnmarkedRecords

**Comment by navinrathore** [comment]
> getUnMarkedRecords - rename to getUnmarkedRecords

* PR #372

**Comment by navinrathore** [comment]
> getUnMarkedRecords - rename to getUnmarkedRecords

* PR #372

**Comment by navinrathore** [comment]
> def getDfFromDs(self, data): return DataFrame(data, sqlContext)
> 
> this gives an error /databricks/spark/python/pyspark/sql/dataframe.py:129: UserWarning: DataFrame constructor is internal. Do not directly use it. warnings.warn("DataFrame constructor is internal. Do not directly use it.")

* PR #373
