### ISSUE TITLE
Test null types for double/integers

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#355]
Build test cases with

csv with double and schema as double
- what is the value returned by getAs when the values are null/0.5 gbp/gbp as values?

ditto for integers

**Comment by navinrathore** [comment]
sample input data and its internal output
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<body>



  |   |   |  
-- | -- | -- | --
**Test Input** | |**Test Output**
Double | Integer | Double | Integer
0.55 | 55 | 0.55 | 55
1.234 | 1234 | 1.234 | 1234
34 | gbp | 34 | null
99.56 | 9956 | 99.56 | 9956
56gbp | 56 | null | 56
23 | 23gbp | 23 | null
  | 45 | null | 45
65 |   | 65 | null
  |   | null | null
0.5 gbp | 23 | null | 23
56 | 56 | 56 | 56
$ | 64 | null | null
null | 34 | null | 34
78 | null | 78 | null
78 | 87 | 78 | 87


</body>

</html>
