### ISSUE TITLE
python api documentation 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#359]
add information and documentation about the classes and methods

**Comment by sonalgoyal** [comment]
use sphinx which can be imported into readthedocs.

**Comment by sonalgoyal** [comment]
@RavirajBaraiya

**Comment by RavirajBaraiya** [comment]
[python documentation.docx](https://github.com/zinggAI/zingg/files/9070879/python.documentation.docx)

**Comment by RavirajBaraiya** [comment]
PR #385

**Comment by sonalgoyal** [comment]
I Installed sphinx and sphinx-rtd-theme. Without any changes to rst etc, I went to docs and ran 
make html

here is what i got:
Running Sphinx v2.0.0

Extension error:
Could not import extension sphinx.ext.duration (exception: No module named 'sphinx.ext.duration')
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2

**Comment by RavirajBaraiya** [comment]
try cmd: pip install -U sphinx, to install sphinx and check if it works or not

**Comment by sonalgoyal** [comment]
Sphinx and the theme are installed
