### ISSUE TITLE
test data documenter breaking

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#363]
break in zingg.documenter.TestDataDocumenter.testIfDataDocumenterGeneratedDocFile(TestDataDocumenter.java:48)
![Screenshot from 2022-06-23 23-36-43](https://user-images.githubusercontent.com/309387/175468903-8df9161d-af7f-4515-98b4-54426a46046b.png)

**Comment by navinrathore** [comment]
DataDocumenter.java and TestDataDocumenter.java have been removed. They do not have any significant functionality.
