### ISSUE TITLE
Zingg Youtube Channel

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#378]
create a youtube channel and add 
- https://www.youtube.com/watch?v=zOabyZxN9b0&t=2s
- https://www.youtube.com/watch?v=zOabyZxN9b0&t=2s
- streamsets video from slack

**Comment by shefalika-thapa** [comment]
Created the YouTube channel Zingg AI: https://www.youtube.com/channel/UCqP3WVqSrfGaKETEuTvSdpw
Uploaded the first Video titled: Identity Resolution With Zingg, Streamsets, Snowflake and Databricks.

**Comment by sonalgoyal** [comment]
https://www.youtube.com/channel/UCqP3WVqSrfGaKETEuTvSdpw
