### ISSUE TITLE
amazon-google example header conflict

### ISSUE THREAD

**Issue by RavirajBaraiya** [zinggAI/zingg#383]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RavirajBaraiya** [comment]
GoogleProduct.csv has header "name" while config.csv has files "title"

**Comment by sonalgoyal** [comment]
90d28ecfc3ce2f59686ea4a065fbb6a1583b49c2
