### ISSUE TITLE
TestGetAs is slow

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#400]
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.14 s - in zingg.hash.TestGetAs

4 seconds is way too long for this test. investigate and suggest what needs to change

**Comment by sonalgoyal** [comment]
here are the slow ones for me

[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.433 s - in zingg.similarity.function.TestNumbersJaccardFunction
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.325 s - in zingg.util.TestDSUtil
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.415 s - in zingg.hash.TestGetAs
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.455 s - in zingg.documenter.TestStopWordsDocumenter
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.389 s - in zingg.documenter.TestDataDocumenter
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.211 s - in zingg.documenter.TestDocumenterBase
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.14 s - in zingg.preprocess.TestStopWords

**Comment by sonalgoyal** [comment]
testgetas setup needs to improve. have separate dfs for int and double. have dfs per case, with 2-3 values max so that long for loops can be avoided

**Comment by vikasgupta78** [comment]
This seems to have been fixed and any time being taken is by ZinggSparkTester to set up session etc. No changes needed.
