### ISSUE TITLE
Get output using our input file

### ISSUE THREAD

**Issue by premsmac2021** [zinggAI/zingg#42]
Hi Sonalgoya, 

In the test.csv, you have the first column called REC ID which already says whether a record is Original or Duplicate. In my case, I have an input file that contains First name, last name and other similar columns that you have in test.csv. How do I use Zingg to find out the duplicates? Is there a pre-processing step I am missing?

**Comment by sonalgoyal** [comment]
the fields to be matched is picked up from the fieldDefinitions, which is not using the record id if you check the config athttps://github.com/zinggAI/zingg/blob/main/examples/febrl/config.json - so go ahead and define your schema and field definitions.

**Comment by premsmac2021** [comment]
Working on data.

**Comment by premsmac2021** [comment]
@sonalgoyal Wow its working good. I am doing analysis with more records..

**Comment by sonalgoyal** [comment]
Awesome @premsmac2021. Closing this issue then
