### ISSUE TITLE
How to run zingg in azure?

### ISSUE THREAD

**Issue by sidharth16395** [zinggAI/zingg#428]
Hi @sonalgoyal ,
I  had tried the one month ago using docker in my local machine able to run and getting result. But now i got data in azure blob so i need to test it and data size is around 50gb.
1. Can we run in azure hdinsight and how to set up?
 2. Need suggestion from your side regarding  how to scalable,cost effective way we can run in azure like  hardware size,etc .

**Comment by sonalgoyal** [comment]
I believe you can use 
a. Azure Databricks and leverage the Databricks Zingg solution accelerator https://www.databricks.com/blog/2022/08/04/new-solution-accelerator-customer-entity-resolution.html
b. Use hdinsights and spark-submit. https://stackoverflow.com/questions/40351290/how-to-submit-jobjar-to-the-azure-spark-cluster-through-commandline-interface. We have not tried this option but it should work as far as I can tell from the documentation
c. For hardware sizing - please check https://docs.zingg.ai/zingg/stepbystep/hardwaresizing

**Comment by sidharth16395** [comment]
![image](https://user-images.githubusercontent.com/104770008/184106059-d899b6e7-99fa-466e-a3cb-a4755bc0b3a5.png)
 if i tried to run ./scripts/zingg.sh --phase trainMatch --conf examples/febrl/config.json
after installing in linux it is showing above error that zingg.sh command not found

**Comment by sonalgoyal** [comment]
Are you running under Zingg home or from scripts? The given command needs to be run from zingg home

**Comment by sidharth16395** [comment]
i am running from below path:
/home/sidubunt/zingg/zingg-0.3.3-SNAPSHOT
now i am getting below error:
./scripts/zingg.sh: line 9: /bin/spark-submit: No such file or directory

**Comment by sonalgoyal** [comment]
please follow the steps detailed at https://docs.zingg.ai/zingg0.3.3/stepbystep/installation. please check that you have set spark home, zingg home and other variables

**Comment by sonalgoyal** [comment]
also, this issue is about running on azure. please open a separate issue for local installation if you still run into a problem.
