### ISSUE TITLE
Match phase fails to save output

### ISSUE THREAD

**Issue by mechanicpanic** [zinggAI/zingg#435]
**Describe the bug**
During the match phase, using my own data, Zingg fails to write the output to disk with the exception `java.io.IOException: Mkdirs failed to create file:/zingg-0.3.4-SNAPSHOT/examples/_temporary/0/_temporary/attempt_202208251755201133149569543965925_0205_m_000007_10662 (exists=false, cwd=file:/zingg-0.3.4-SNAPSHOT)`

I am running Zingg 0.3.4 on WSL Ubuntu 20.04 on Windows 10. This was the case with Zingg 0.3.3 as well, however, Zingg 0.3.3 did save the output of the pretrained Febrl models with no issues.

One thing I tried was running `sudo docker start` on the container, but it did not help.

**Comment by mechanicpanic** [comment]
Ah, yes, I overlooked that in my config. Saving to a different path did work. Thanks!

**Comment by sonalgoyal** [comment]
That’s cool, congrats!
