### ISSUE TITLE
findtraining phase taking  large time

### ISSUE THREAD

**Issue by sidharth16395** [zinggAI/zingg#436]
It has been stuck for more then 4hrs below is the screenshot and data is around 50 lakhs and i had kept labled sample size 0.5 i.e reason its taking time right
![image](https://user-images.githubusercontent.com/104770008/186790942-81742920-5e82-41e2-a075-e859a7e3ad99.png)

**Comment by sonalgoyal** [comment]
Yes you can reduce the sample size or go to a bigger driver machine

**Comment by sidharth16395** [comment]
> Yes you can reduce the sample size or go to a bigger driver machine

yes got it let me try it thanks.
