### ISSUE TITLE
InmemoryPipe is not working 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#441]
[
<img width="1440" alt="Screenshot 2022-09-30 at 10 28 37 PM" src="https://user-images.githubusercontent.com/309387/193320299-4392715b-7378-46e5-b1a1-13593886cbbc.png">
](url)

As we changed the formats from enum to strings, we did not change the subsequent check in PipeUtil line 77
if (p.getFormat() == Pipe.FORMAT_INMEMORY) {
			input = ((InMemoryPipe) p).getRecords();
		}

thus the in mem pipe is no longer working. Attaching python program to test this 
[memTry.py.txt](https://github.com/zinggAI/zingg/files/9686403/memTry.py.txt)

**Comment by sonalgoyal** [comment]
fixed through dc9f906e6bea04d16cfdbb653a36b5f5b60c7cb7

**Comment by sonalgoyal** [comment]
still need to check why pandas set df is not working

**Comment by sonalgoyal** [comment]
saw this working on 0.3.5 - @vikasgupta78 can you please check if the pandas stuff is working as well and we can close

**Comment by vikasgupta78** [comment]
Working fine in 0.3.5 with pandas@1.5.3

There seems to be an issue with padas 2.0 due to removal of iteritems and getting same error as mentioned in below git issue:

https://github.com/YosefLab/Compass/issues/92
