### ISSUE TITLE
Model Reading and Writing to Blob Storage Fails

### ISSUE THREAD

**Issue by karthik1289** [zinggAI/zingg#450]
When the Model Directory is set to S3 or any other blob storage, zinng job never completes. Below is the stack trace for the same.
`[3:18 PM] Writing output Pipe [name=null, format=parquet, preprocessors=null, props={location=s3a://sparkcluster-data/demo3/models/100/model/block/zingg.block}, schema=null]
22/10/28 09:40:23 WARN PipeUtil: Writing file
22/10/28 09:41:04 WARN InstanceBuilder$NativeBLAS: Failed to load implementation from:dev.ludovic.netlib.blas.JNIBLAS
22/10/28 09:41:04 WARN InstanceBuilder$NativeBLAS: Failed to load implementation from:dev.ludovic.netlib.blas.ForeignLinkerBLAS
22/10/28 09:41:04 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
22/10/28 09:41:04 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

22/10/28 09:44:25 ERROR TaskSchedulerImpl: Lost executor 2 on 10.244.4.13: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
22/10/28 09:44:25 ERROR TaskSchedulerImpl: Lost executor 3 on 10.244.2.3: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
22/10/28 09:44:25 ERROR TaskSchedulerImpl: Lost executor 0 on 10.244.6.5: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
22/10/28 09:44:25 ERROR TaskSchedulerImpl: Lost executor 1 on 10.244.5.5: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.`

**Comment by sonalgoyal** [comment]
Thanks @karthik1289 - how many times have you tried?

**Comment by vikasgupta78** [comment]
pull request #550 commit ce90ce7

**Comment by vikasgupta78** [comment]
need to make it work without public access to the bucket

**Comment by vikasgupta78** [comment]
fixed via commit 0b748a2c
