### ISSUE TITLE
Missing snowflake dependencies during mvn clean compile package [Local Dev Environment]

### ISSUE THREAD

**Issue by abhay447** [zinggAI/zingg#451]
**Describe the bug**
Missing snowflake dependencies during mvn clean compile package [Local Dev Environment]

**To Reproduce**
1. Follow steps 1-5 of the local dev environment setup doc : https://docs.zingg.ai/zingg/contributing/settingupzingg
2. Run : `mvn clean compile package -Dspark=3.1.2`
3. Command fails with error: `/home/abhay/work/zingg/zingg/client/src/test/java/zingg/client/TestSnowFrame.java:[12,35] package com.snowflake.snowpark_java does not exist`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8853204/201181887-03bb476a-d213-471a-adfb-27733ff7382f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu-20.04 [running on WSL2]

**Additional context**

**Comment by sonalgoyal** [comment]
Interesting- seems like we have this test class by mistake in this branch. Can you please remove it and try again?

**Comment by sonalgoyal** [comment]
Great, feel free to submit a pr
