### ISSUE TITLE
Shutdown hook manager 

### ISSUE THREAD

**Issue by Dhyani01** [zinggAI/zingg#456]
Did everything by the books/documentation, was running febrl example.

At the end of labeling, I get this error and it just deletes the progress.
Why I am facing this issue?
![Screenshot from 2022-11-18 13-54-56](https://user-images.githubusercontent.com/41862180/202656229-3cb4e0bf-595e-4433-9244-f007ef43b809.png)

**Comment by sonalgoyal** [comment]
Hi @Dhyani01, thanks for trying Zingg. The image above shows temporary files getting deleted, which should be ok. Can you run trainMatch if you have done one round of findTrainingData and label and see if you get the results?

**Comment by Dhyani01** [comment]
@sonalgoyal Hey thanks for the quick reply can you help me with how can I train my data till I get sufficient results?
Currently while executing this command (./scripts/zingg.sh --phase label --conf examples/folder/config.json)
Training stops after 10 training match samples.
How to keep going on till I get enough matches such that my model can understand the pattern.

**Comment by sonalgoyal** [comment]
that's strange. the logs seem to suggest writing to file:/tmp/zinggOutput. Are you using the default config and febrl example?

**Comment by Dhyani01** [comment]
yes, @sonalgoyal while working with config file of febrl example and my own dataset, I am not getting any output.

**Comment by sonalgoyal** [comment]
Can you please share the full log ?

**Comment by Dhyani01** [comment]
@sonalgoyal It was some spark issue, Thanks for the help.

**Comment by sonalgoyal** [comment]
Perfect, thanks @Dhyani01
