### ISSUE TITLE
Issue running 400k records in docker

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#459]
I am not sure what is occurring. i can run `findTrainingData` on the exact same files with the exact same configuration and it gets hung up at completely different spots. sometimes right on launch, other times when reading in the first file, sometimes when it gets to `Preprocessing DS for stopWords`. one time when writing the file. but, I can’t get it to complete

[Slack Message](https://zinggai.slack.com/archives/C02JNH144TB/p1668802936771799?thread_ts=1668706272.867209&cid=C02JNH144TB)

**Comment by sonalgoyal** [comment]
mac issue with docker, created new image f5c18c628ad9771b0e8972d4cec144db13becec9

**Comment by sonalgoyal** [comment]
we can probably use the same dockerfile for both. also see how we will publish for different architecture using same dockerfile. --platform option?

**Comment by vikasgupta78** [comment]
Steps tried:

1. Make docker image on ubuntu and test the same

    1. Install using https://docs.docker.com/engine/install/ubuntu/
    (chose Install using the apt repository option)
    2. sudo su
    3. sudo docker image build -t zingg/vikas .
    4. now go to /tmp
    5. docker run -v /tmp:/tmp -it zingg/vikas bash
    6. ./scripts/zingg.sh --phase findTrainingData --conf examples/febrl/config.json --zinggDir /tmp/z_docker


3. Now take dump of the image , sftp and run it on mac:

sudo docker save zingg/vikas:latest | gzip > myimage_latest.tar.gz

To now load using above after sftp

docker load < myimage_latest.tar.gz

to get list:

docker images

now run:
cd /tmp
docker run -v /tmp:/tmp -it zingg/vikas bash

Getting following warning:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by vikasgupta78** [comment]
what is needed is to make a multi platform image

Tried the buildx option but it causes issues while making, uploading etc. So instead of that going with manifest option:

Reference :

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

in summary 
arm64 image needs to be made on mac => pushed
amd64 image needs to be made on ubuntu => pushed
then a manifest file combining the two above into a latest tag needs to be pushed

Steps done:


on mac:

    docker build -t <docker-username>/<image-name>:arm64v8 --build-arg ARCH=arm64v8/ .

    docker push <docker-username>/<image-name>:arm64v8


on ubuntu:
      sudo su
      docker login => give username and password

      docker build -t <docker-username>/<image-name>:amd64 --build-arg ARCH=amd64/ .

      docker push <docker-username>/<image-name>:amd64

      docker manifest create \
      <docker-username>/<image-name>:latest \
      --amend <docker-username>/<image-name>:amd64 \
      --amend <docker-username>/<image-name>:arm64v8

      docker manifest push <docker-username>/<image-name>:latest

**Comment by vikasgupta78** [comment]
Pull request #590 commits 280ef3bf , 0b279733
