### ISSUE TITLE
Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo

### ISSUE THREAD

**Issue by dougscc** [zinggAI/zingg#470]
Attempting to build `zingg` using the [instructions here](https://docs.zingg.ai/zingg/stepbystep/installation/compiling-from-source)  with `mvn -U clean compile package -Dspark=3.1`, which results in the error:

```bash
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project zingg:core:jar:0.3.4-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/) -> [Help 1]
```

Not well versed in Java, so If this is some incredibly humiliating noob problem, apologies in advance. It does appear to me that a particular package could not be downloaded.

System is:
```bash
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

Java version:
```bash
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```

Maven version:
```bash
$ mvn -version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_352, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el7_9.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-1160.31.1.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by dougscc** [comment]
I did find the package, with the correct version at https://mvnrepository.com/artifact/com.wcohen/com.wcohen.secondstring. Artifact appears to be there. Sorry, not smart enough to figure this out.

**Comment by sonalgoyal** [comment]
Thanks for trying Zingg out and reporting this issue! The package is part of the Zingg repo ( zingg/thirdParty/lib/secondstring.jar), and is picked up from there instead of getting downloaded from the net. So you should not have to download or add it separately. 

What happens when you run mvn process-resources ? Do you get an error but at the same time, the logs have something that indicates that the secondstring jar is being installed to the maven local repo? For example, this is part of the log on my machine. 

--- maven-install-plugin:2.5.2:install-file (install-external) @ parent ---
[INFO] pom.xml not found in secondstring.jar
[INFO] Installing /Users/sonal/zingg/thirdParty/lib/secondstring.jar to /Users/sonal/.m2/repository/com/wcohen/ss/secondstring/2021/secondstring-2021.jar
[INFO] Installing /var/folders/kc/jgyc0yt506l9yw6yt924vbdw0000gn/T/mvninstall6738455072140525902.pom to /Users/sonal/.m2/repository/com/wcohen/ss/secondstring/2021/secondstring-2021.pom

**Comment by dougscc** [comment]
@sonalgoyal, here is a dump from `mvn process-resources`:

```bash
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for zingg:core:jar:0.3.4-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ zingg:parent:${zingg.version}, /home/someguy@somewhere/Projects/zingg/pom.xml, line 5, column 11
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for zingg:parent:pom:0.3.4-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ zingg:parent:${zingg.version}, /home/someguy@somewhere/Projects/zingg/pom.xml, line 5, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] client
[INFO] core
[INFO] zingg
[INFO] parent
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building client 0.3.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ client ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ client ---
[INFO] Add Source directory: /home/someguy@somewhere/Projects/zingg/client/src/main/scala
[INFO] Add Test Source directory: /home/someguy@somewhere/Projects/zingg/client/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ client ---
[WARNING]  Expected all dependencies to require Scala version: 2.12.11
[WARNING]  org.scala-lang.modules:scala-parser-combinators_2.12:1.1.2 requires scala version: 2.12.8
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building core 0.3.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.wcohen.ss:secondstring:jar:2021 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] client ............................................ SUCCESS [3.413s]
[INFO] core .............................................. FAILURE [0.143s]
[INFO] zingg ............................................. SKIPPED
[INFO] parent ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.676s
[INFO] Finished at: Tue Dec 13 08:44:29 EST 2022
[INFO] Final Memory: 31M/688M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project zingg:core:jar:0.3.4-SNAPSHOT: Failure to find com.wcohen.ss:secondstring:jar:2021 in https://repos.spark-packages.org/ was cached in the local repository, resolution will not be reattempted until the update interval of SparkPackagesRepo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core
```

**Comment by dougscc** [comment]
@sonalgoyal a full dump of `mvn -U -X clean compile package -Dspark=3.1` is a bit too big to subject you to, I'm thinking. :) I did grep out the references to `seconstring.jar`, however:

```bash
[WARNING] The POM for com.wcohen.ss:secondstring:jar:2021 is missing, no dependency information available
[DEBUG]    com.wcohen.ss:secondstring:jar:2021:compile
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project zingg:core:jar:0.3.4-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project core: Could not resolve dependencies for project zingg:core:jar:0.3.4-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project zingg:core:jar:0.3.4-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/)
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/)
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in SparkPackagesRepo (https://repos.spark-packages.org/)
```

**Comment by sonalgoyal** [comment]
@dougscc thanks! lets try to manually install the jar to your repo and see if that helps. other than the maven version(mine is 3.8.6), I dont see any other difference between your env and mine. 

Can you please try and tell me what could be going wrong?
mvn install:install-file -Dfile=thirdParty/lib/secondstring.jar -DgroupId=com.wcohen.ss -DartifactId=secondstring -Dversion=2021 -Dpackaging=jar -DgeneratePom=true

**Comment by sonalgoyal** [comment]
Also, I see that your spark version is 3.1 for which we have the release (https://github.com/zinggAI/zingg/releases/tag/v0.3.4). Is there something specific in the latest code that you are trying to compile?

**Comment by dougscc** [comment]
> @dougscc thanks! lets try to manually install the jar to your repo and see if that helps. other than the maven version(mine is 3.8.6), I dont see any other difference between your env and mine.
> 
> Can you please try and tell me what could be going wrong? `mvn install:install-file -Dfile=thirdParty/lib/secondstring.jar -DgroupId=com.wcohen.ss -DartifactId=secondstring -Dversion=2021 -Dpackaging=jar -DgeneratePom=true`

It appears that the manual install of the `jar` worked:

```bash
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 0.3.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install-file (default-cli) @ parent ---
[INFO] pom.xml not found in secondstring.jar
[INFO] Installing /home/someguy@somewhere/Projects/zingg/thirdParty/lib/secondstring.jar to /home/someguy@somewhere/.m2/repository/com/wcohen/ss/secondstring/2021/secondstring-2021.jar
[INFO] Installing /tmp/mvninstall5621067722660198309.pom to /home/someguy@somewhere/.m2/repository/com/wcohen/ss/secondstring/2021/secondstring-2021.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] client ............................................ SKIPPED
[INFO] core .............................................. SKIPPED
[INFO] zingg ............................................. SKIPPED
[INFO] parent ............................................ SUCCESS [0.160s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.156s
[INFO] Finished at: Tue Dec 13 09:06:50 EST 2022
[INFO] Final Memory: 12M/193M
[INFO] ------------------------------------------------------------------------


```

**Comment by dougscc** [comment]
> Also, I see that your spark version is 3.1 for which we have the release (https://github.com/zinggAI/zingg/releases/tag/v0.3.4). Is there something specific in the latest code that you are trying to compile?

I was just working from the docs: https://docs.zingg.ai/zingg/stepbystep/installation/compiling-from-source

3.1 is the latest version. Big number good, right?

**Comment by sonalgoyal** [comment]
Cool, lets try `mvn clean compile package -DskipTests=true` and see if the compile can pick up the lib

**Comment by sonalgoyal** [comment]
> > Also, I see that your spark version is 3.1 for which we have the release (https://github.com/zinggAI/zingg/releases/tag/v0.3.4). Is there something specific in the latest code that you are trying to compile?
> 
> I was just working from the docs: https://docs.zingg.ai/zingg/stepbystep/installation/compiling-from-source
> 
> 3.1 is the latest version. Big number good, right?

Yes. Sorry if the doc confused you. If you don't want the latest code or have a different spark version, download of the release should work. The docker has everything(spark, python) preinstalled too, just in case that was not clear for the docs.

**Comment by dougscc** [comment]
I got a bit hasty and am running `mvn compile package -Dspark=3.1`. I was concerned that `clean` would wipe out anything I have previously installed out-of-band (again, working from just enough knowledge to cause myself pain). 

However, it does appear that something went right:

```bash
[INFO] Reactor Summary:
[INFO]
[INFO] client ............................................ SUCCESS [6.129s]
[INFO] core .............................................. SUCCESS [2:42.045s]
[INFO] zingg ............................................. SUCCESS [57.187s]
[INFO] parent ............................................ SUCCESS [0.243s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:45.723s
[INFO] Finished at: Tue Dec 13 09:13:28 EST 2022
[INFO] Final Memory: 69M/1158M
[INFO] ------------------------------------------------------------------------
```

I can nuke this install and try again from scratch, if that will help you with understanding what went wrong in the first place. I have the feeling that an experienced java person in a hurry would make a noise, then install `secondstring` without reporting it, as I probably would when someone forgot to add a dependency in a python module. :)

I am at your disposal, here.

**Comment by dougscc** [comment]
> Yes. Sorry if the doc confused you. If you don't want the latest code or have a different spark version, download of the release should work. The docker has everything(spark, python) preinstalled too, just in case that was not clear for the docs.

Can't use docker, for reasons. :/

The docs are fine, I'm sure I am just operating from too much haste and too little context.

Again, if you need me to wipe `zingg` and attempt the build again, in order to better isolate the issue, I am glad to help.

**Comment by sonalgoyal** [comment]
This is cool, congrats @dougscc - you have crossed over to the bridge from python to java development 👍 🥇 

Instead of you trying to replicate this issue, I would very much love for Zingg to deliver some value to you as a user. Is there something I can answer for you? Want to schedule some time to go over your installation and context? (My calendar is on the readme :) )

**Comment by dougscc** [comment]
Thanks @sonalgoyal, I'll let you know if I can't figure out the various config files. :)

To misquote someone smarter than me: "I am a java developer the way a piano falling down the stairs is a symphony".

**Comment by sonalgoyal** [comment]
@dougscc - I think you will enjoy the python api much more than the json. https://docs.zingg.ai/zingg/working-with-python. looking forward to your feedback!

**Comment by sonalgoyal** [comment]
keeping this open to track if others face the same issue

**Comment by sonalgoyal** [comment]
closing this as no user has reported an issue
