### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by dougscc** [zinggAI/zingg#479]
Attempting to follow the [Step by Step Identity Resolution](https://towardsdatascience.com/step-by-step-identity-resolution-with-python-and-zingg-e0895b369c50) article. Got this far:

```python
from zingg.client import *
from zingg.pipes import *

#build the arguments for zingg
args = Arguments()
```
... and ran into:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thisfoolhere/Projects/zingg/.direnv/python-venv-3.8.15/lib/python3.8/site-packages/zingg/client.py", line 188, in __init__
    self.args = jvm.zingg.client.Arguments()
TypeError: 'JavaPackage' object is not callable
```

**To Reproduce**
1. Install the following in a virtual environment: `numpy==1.24.1 pandas==1.5.2 py4j==0.10.9 pyspark==3.1.3 python-dateutil==2.8.2 pytz==2022.7 six==1.16.0 zingg==0.3.4`
    1. I had to install numpy and pandas independently of `zingg`, since the package does not seem to have particular versions as dependencies.
1. run the snippet above

**Expected behavior**
Creation of `args` object.

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu

**Comment by sonalgoyal** [comment]
Thanks for trying Zingg @dougscc. Zingg python programs are dependent on Spark and Zingg java code. The tutorial was written using our docker which has everything pre installed. So you can use that or do a Zingg installation as per the docs and try again. Hope this helps

**Comment by sonalgoyal** [comment]
@dougscc - please let me know if you need help on this.

**Comment by dougscc** [comment]
I'll keep hacking on it until it works. Thanks.

**Comment by avinashkurup** [comment]
> 

Hi @dougscc were you able to solve this issue, I'm facing this while trying to run /examples/amazon-google, could you please help.
also @sonalgoyal could you please point me to the tutorial with instructions to fix this issue?

**Comment by sonalgoyal** [comment]
@avinashkurup - what’s your environment like? Local install, docker, hosted cloud service like emr or Databricks?

**Comment by avinashkurup** [comment]
> @avinashkurup - what’s your environment like? Local install, docker, hosted cloud service like emr or Databricks?

Thanks @sonalgoyal, Im facing this issues in docker as well as local install.

**Comment by avinashkurup** [comment]
This is the error in the docker container, Please check @sonalgoyal 

![Screenshot_2023-04-05_17-29-01](https://user-images.githubusercontent.com/681657/230074355-501061fb-b357-4ac8-abef-cee21d26cb7c.png)

**Comment by dougscc** [comment]
> > 
> 
> Hi @dougscc were you able to solve this issue, I'm facing this while trying to run /examples/amazon-google, could you please help. also @sonalgoyal could you please point me to the tutorial with instructions to fix this issue?

Sorry, I was not.

**Comment by sonalgoyal** [comment]
Thanks for sharing this screenshot @avinashkurup. Zingg python programs need to be run using the provided zingg.sh script. Please refer to the last lines here https://docs.zingg.ai/zingg-0.3.4/working-with-python 

@dougscc - hope this helps you as well. Please let me know if you are still facing this or some other issue

**Comment by avinashkurup** [comment]
Thank you @sonalgoyal it worked with the --run option.
