### ISSUE TITLE
Issue on running --phase train

### ISSUE THREAD

**Issue by premsmac2021** [zinggAI/zingg#49]
WARN  org.apache.spark.ml.util.Instrumentation - [7dacb264] All labels are the same value and fitIntercept=true, so the coefficients will be zeros. Training is not needed.
INFO  org.apache.spark.ml.util.Instrumentation - [aa3fb364] training finished
INFO  org.apache.spark.ml.util.Instrumentation - [e20e40e0] training finished
ERROR org.apache.spark.ml.util.Instrumentation - org.apache.spark.SparkException: Exception thrown in awaitResult: 
at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)

WARN  zingg.client.util.Email - Unable to send email Can't send command to SMTP host
WARN  zingg.client.Client - Apologies for this message. Zingg has encountered an error. Exception thrown in awaitResult: 

findTrainingData and Label completed

**Comment by sonalgoyal** [comment]
How many positive and negative pairs have you labeled? The logs say "All labels are the same value and fitIntercept=true, so the coefficients will be zeros. Training is not needed." which means that there are possibly no positive pairs?

**Comment by premsmac2021** [comment]
+-------+---------+------+-----------+---------------------+--------------+--------+--------------+--------+-------------+---------+------------+----------+----------+-------------+-----------+---+------+--------+--------+----+----+-----------+------------+-----------+--------+
|fname  |TALUKNAME|GPNAME|VILLAGENAME|SCHEMENAME           |SERIESYEARNAME|BENFCODE|SPOUSENAME    |BENFNAME|HUSBAND      |CASTENAME|RELIGIONNAME|GENDERNAME|OCCUPATION|TOTALFAMILYNO|ADDRESS    |AGE|AADHAR|VERIFIED|PHONENUM|VC  |VI  |VRATIONCARD|NEWACCOUNTNO|GOLDENRECNO|z_source|
+-------+---------+------+-----------+---------------------+--------------+--------+--------------+--------+-------------+---------+------------+----------+----------+-------------+-----------+---+------+--------+--------+----+----+-----------+------------+-----------+--------+
|RAJAMMA|Mysuru   |Varuna|Chikkahalli|Basava Housing Scheme|2015 2016     |265342  |CHIKKAMUTTAIAH|rajam ma|cikkamuttayya|SC       |Hindu       |Female    |Labour    |3            |CHIKKAHALLI|36 |null  |No      |null    |null|null|null       |85034963709 |5910841    |test    |
|RAJAMMA|Mysuru   |Varuna|Chikkahalli|Basava Housing Scheme|2015 2016     |265342  |CHIKKAMUTTAIAH|rajam ma|cikkamuttayya|SC       |Hindu       |Female    |Labour    |3            |CHIKKAHALLI|36 |null  |No      |null    |null|null|null       |85034963709 |5910841    |test    |
+-------+---------+------+-----------+---------------------+--------------+--------+--------------+--------+-------------+---------+------------+----------+----------+-------------+-----------+---+------+--------+--------+----+----+-----------+------------+-----------+--------+


	Please select from the following choices
	No, they do not match : 0
	Yes, they match       : 1
	Not sure              : 2

	To exit               : 9

	Please enter your choice [0,1,2 or 9]: 1

	Record pair 11 out of 22 records to be labelled by the user.
	Zingg predicts the records ARE NOT KNOWN IF MATCH with a similarity score of 0.00

**Comment by sonalgoyal** [comment]
sorry I did not understand your last comment

**Comment by premsmac2021** [comment]
Above is the positive pair. but issue message says that there are possibly no positive pair. 
and not producing the trained records in tmp folder.

**Comment by sonalgoyal** [comment]
How many positive pairs do you have? You need at least 20-30 pairs for the classifier to get trained on

**Comment by premsmac2021** [comment]
Record pair 21 out of 22 records to be labelled by the user.
	Zingg predicts the records ARE NOT KNOWN IF MATCH with a similarity score of 0.00

What is the score ? If record 
No, they do not match 
or
Yes, they match means?

**Comment by sonalgoyal** [comment]
sorry again I did not understand the comment above.

**Comment by premsmac2021** [comment]
Can you please refer this.

**Record not matching**
	Please select from the following choices
	No, they do not match : 0
	Yes, they match       : 1
	Not sure              : 2

	To exit               : 9

	Please enter your choice [0,1,2 or 9]: 0

	Record pair 17 out of 20 records to be labelled by the user.
	Zingg predicts the records MATCH with a similarity **score of 1.00**
-------------------------------------------------------------------------
**Record Matching:-**
	Please select from the following choices
	No, they do not match : 0
	Yes, they match       : 1
	Not sure              : 2

	To exit               : 9

	Please enter your choice [0,1,2 or 9]: 1

	Record pair 18 out of 20 records to be labelled by the user.
	Zingg predicts the records DO NOT MATCH with a similarity **score of 0.27**
-------------------------------------
	Please select from the following choices
	No, they do not match : 0
	Yes, they match       : 1
	Not sure              : 2

	To exit               : 9

	Please enter your choice [0,1,2 or 9]: 1

	Record pair 19 out of 20 records to be labelled by the user.
	Zingg predicts the records MATCH with a similarity **score of 1.00**


Here I've given 2 scenarios, 1st one record doesn't match 2nd & 3rd one records are matching. But score's are showing different.

Do you understand?

**Comment by sonalgoyal** [comment]
The labelling phase scores are indicative and get refined as you add more samples. How many pairs have you labelled so far? How many positives?

**Comment by premsmac2021** [comment]
Out of 21, 15 Positives

Positive means same record?

**Comment by sonalgoyal** [comment]
Yes, positive means they are same. How many total rounds have you run? Have you labelled 15 pairs as yes out of total 21 or is it in this round?

**Comment by premsmac2021** [comment]
labelled 15 pairs as yes out of total 21.

**Comment by sonalgoyal** [comment]
Ok, that’s pretty good to find so many matches in the first round of labelling itself. Do a few more rounds till you have about 30-49 matches and then try trainMatch

**Comment by premsmac2021** [comment]
Yes, will do that..

**Comment by premsmac2021** [comment]
what is the length of header name?

I've given this length.
MEMBER_OCCUPATION_ID_DESCRIPTION

**Comment by sonalgoyal** [comment]
Is there a problem?

**Comment by premsmac2021** [comment]
didn't accept the  "_" underscore

**Comment by sonalgoyal** [comment]
oh, looks like a bug, opened #50 for that. thanks for reporting. please add any other observations related to that issue there.

**Comment by sonalgoyal** [comment]
Is the training issue sorted @premsmac2021 - if so, can you please close this issue or let me know?
