### ISSUE TITLE
python phase assessmodel not working post refactoring

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#519]
assessmodel is broken due to peek model being out of sync

**Comment by sonalgoyal** [comment]
can you please verify this @vikasgupta78 ? should be fixed in 0.3.5

**Comment by vikasgupta78** [comment]
./scripts/zingg.sh --phase exportModel --conf examples/febrl/config.json --location /tmp/z_export

above worked fine and the model was written in target directory
