### ISSUE TITLE
git lfs issue while cloning repo

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#52]
A user reported git lfs issue while cloning the repo. need to verify the steps and fix cloning instructions

**Comment by sonalgoyal** [comment]
i have made some changes - can you please verify  @navinrathore?

**Comment by navinrathore** [comment]
The Cloning operation still requires git-lfs.
Here is the error in absence of git-lfs:
.....
**Resolving deltas: 100% (886/886), done.
git-lfs filter-process: 1: git-lfs: not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.**
......
Also, here is the message when git-lfs is available:
.......
**Encountered 6 file(s) that should have been pointers, but weren't:
	examples/febrl120k/test.csv**
........

**Comment by sonalgoyal** [comment]
thanks, can you please test now? @navinrathore

**Comment by navinrathore** [comment]
Verified.
Clone works fine in both the cases i.e. not dependent on git-lfs package.

**Comment by sonalgoyal** [comment]
Perfect, thanks @navinrathore - closing this
