### ISSUE TITLE
sparkclient as well as sparkzinggcontext both have session creation

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#521]
the default constructor of sparkclient is building the spark session. but we are building it in the zinggsparkcpntext as well. this is hurting the python phases. not sure if there are other possible impacts. need to check again.

**Comment by sonalgoyal** [comment]
@vikasgupta78 - this seems fixed, right? can you please verify.

**Comment by vikasgupta78** [comment]
the default constructor of sparkclient is no longer building the spark session
