### ISSUE TITLE
databricks new interface is broken in generics code

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#538]
As we are not passing spark as part of the client code, the following will fail 

if (self.phase == 'label'):
           self.client = jvm.zingg.spark.client.SparkClient(args.getArgs(), options.getClientOptions())
        else:
            self.client = jvm.zingg.spark.client.SparkClient(args.getArgs(), options.getClientOptions(), spark._jsparkSession)
        try:
            self.isRemote = options.getClientOptions().getOptionValue(ClientOptions.REMOTE)
        except:

**Comment by sonalgoyal** [comment]
@vikasgupta78 - ok to close this with the new pr?

**Comment by vikasgupta78** [comment]
As we are now giving option of data bricks connect I think this should not be a requirement any longer.
