### ISSUE TITLE
Documenter code review - minor changes

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#545]
In Documenter, PAIR_WISE_COUNT is the count column. 
having that as z_ will make sure we are not interfering with user columns by any chance. So let us change that by adding ColName prefix and make the name start with lower case consistent with other columns we introduce.

**Comment by vikasgupta78** [comment]
Pull request https://github.com/zinggAI/zingg/pull/546 , commit e8020d9
