### ISSUE TITLE
Undo for Interactive Labelling

### ISSUE THREAD

**Issue by salmanea** [zinggAI/zingg#553]
**Is your feature request related to a problem? Please describe.**
During the interactive labeling, one might by mistake, choose the wrong option between "no match", "match" and "uncertain".

**Describe the solution you'd like**
A very good feature would be to be able to undo the choice you made for the previous candidate in the interactive labeling.

**Describe alternatives you've considered**

**Additional context**

**Comment by sonalgoyal** [comment]
Thanks for reporting @salmanea. Zingg does have the facility to update labels. Please check  https://docs.zingg.ai/zingg/stepbystep/createtrainingdata/updatinglabels and let us know what you think.
