### ISSUE TITLE
Null pointer exception running 0.3.4 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#561]
I'm encountering this Java NullPointException error when I run this command line:
&gt; ./scripts/zingg.sh --phase findTrainingData --conf configNewSample.json
I have attached my csv, config file and error logs.

[Slack Message](https://zinggai.slack.com/archives/C02JNH144TB/p1680545966635169?thread_ts=1680538127.332759&cid=C02JNH144TB)

**Comment by vikasgupta78** [comment]
we were able to reproduce the issue

Issue occurs if the csv has really low data

what we did was for one of our working examples : examples/febrl/test.csv, we reduced the number of rows to just 5 and got null pointer at exact same line

once the number of records was increased the error disappeared

**Comment by sonalgoyal** [comment]
Let us give a helpful message here instead of a null pointer

**Comment by vikasgupta78** [comment]
yes we could identify it in the preprocessing stage that the data is too low and give a better message

**Comment by vikasgupta78** [comment]
[zingg Java NullPointerException error (2).txt](https://github.com/zinggAI/zingg/files/11166667/zingg.Java.NullPointerException.error.2.txt)

**Comment by vikasgupta78** [comment]
issue is coming because in BlockingTreeUtil line 62 Tree<Canopy> blockingTree = cblock.getBlockingTree(null, null, root,fd); 

blockingTree returned is null due to lack of data

**Comment by vikasgupta78** [comment]
better exception message when blocking tree is null due to insufficient data

commit fc2db88
pull request #564
