### ISSUE TITLE
Windows: Error occurred while installing Zingg via python

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#563]
pip install zingg giving error

Python 3.10.9 on Windows 11

Error details:

https://zinggai.slack.com/files/U0512BNTYFK/F051XLGD67M/pipinstallzinggerror.txt?origin_team=T02G7KZC7R6&origin_channel=C02JNH144TB

**Comment by vikasgupta78** [comment]
[pipInstallZinggError.txt](https://github.com/zinggAI/zingg/files/11161293/pipInstallZinggError.txt)

**Comment by sonalgoyal** [comment]
@vikasgupta78 - can you please check this and fix/close as necessary?

**Comment by sonalgoyal** [comment]
windows is not a supported platform for now. closing.
