### ISSUE TITLE
documentation broken links

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#57]
https://docs.zingg.ai/docs/setup/configuration.html - pipes links are broken

**Comment by sonalgoyal** [comment]
broken: https://docs.zingg.ai/docs/faq.html#how-much-training-is-enough hardware sizing

**Comment by sonalgoyal** [comment]
https://docs.zingg.ai/docs/pretrainedModels.html

**Comment by navinrathore** [comment]
Duplicate of #59
