### ISSUE TITLE
Regenerate all models

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#573]
Regenerate all models once code is frozen

**Comment by gnanaprakash-ravi** [comment]
Regenerated models for
100 - febrl
101 - febrl120k
102 - it is not running, the config120.json in the databricks folder
103 - amazongoogle
104 - ncVoters - i think my laptop ram is insufficient, and i am getting gc overhead exceeded.
105 - iTunesamazon
106 - beerAdvo
