### ISSUE TITLE
Bug when source contains column names cluster

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#578]
Hi Zingg team, I would like to submit a bug. Sorry if this is the wrong place to do so.

So I encountered this error when trying to input a dataset that had a column with the name "cluster". After I renamed the column name from "cluster" to "group_id", the findTrainingData phase worked fine. The version of Zingg I used was 0.3.4.

[Slack Message](https://zinggai.slack.com/archives/C02JNH144TB/p1682982857829929?thread_ts=1682982857.829929&cid=C02JNH144TB)

**Comment by Vishal0540** [comment]
Hi @sonalgoyal 
I noticed that there is an issue regarding a conflict with the "cluster" variable when using a dataset with a column named "cluster"
in TrainingDataFinder.java
I want to take this issue and work on resolving it. I would appreciate your guidance on any specific guidelines or processes I should follow for contributing the fix.
Thank you for your attention to this matter, and I appreciate the opportunity to contribute to the project.

**Comment by sonalgoyal** [comment]
Thanks we are not planning to fix this for now
