### ISSUE TITLE
databricks api 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#579]
Explore databricks api.

Few things to keep in mind
a. Same interface using zingg.sh
b. label should happen locally 
c. match should work independently. Early tests show that trainMatch and train individually succeed but match fails with  java.lang.ClassNotFoundException: org.apache.spark.ml.feature.PolynomialExpansion$client08d4e63a2f$$typecreator1$1

**Comment by vikasgupta78** [comment]
If trainMatch works , match can only fail if train match is creating instance of a different matcher
