### ISSUE TITLE
Python package referencing wrong license details

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#581]
Though the package says AGPL, the license file referred to in one case is apache. Need to fix that

**Comment by vikasgupta78** [comment]
most probable change in setup.py line 175

python/setup.py:
  175:         license='http://www.apache.org/licenses/LICENSE-2.0',

**Comment by vikasgupta78** [comment]
license url change pull request #585 , commit 0443fb3c

Now showing as (after the change):
vikasgupta@Vikass-MacBook-Air zingg-vikas % pip show zingg
Name: zingg
Version: 0.3.5
Summary: Zingg Entity Resolution, Data Mastering and Deduplication
Home-page: https://github.com/zinggAI/zingg
Author: Zingg.AI
Author-email: sonalgoyal4@gmail.com
License: https://github.com/zinggAI/zingg/blob/main/LICENSE
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: py4j
Required-by: 

Earlier showing as:
vikasgupta@Vikass-MacBook-Air zingg-vikas % pip show zingg
Name: zingg
Version: 0.3.5
Summary: Zingg Entity Resolution, Data Mastering and Deduplication
Home-page: https://github.com/zinggAI/zingg
Author: Zingg.AI
Author-email: sonalgoyal4@gmail.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: py4j
Required-by:
