### ISSUE TITLE
Zingg on spark-operator enabled K8 cluster

### ISSUE THREAD

**Issue by pejathayaS** [zinggAI/zingg#589]
I am trying to run zingg  python code on a cluster which has google spark-operator enabled. 

I have created a base docker image which has the run time properties of zingg along with pyspark 3.1.2 .
Using the above spark base image I am trying to run the example [examples](https://github.com/zinggAI/zingg/tree/main/examples)/[febrl](https://github.com/zinggAI/zingg/tree/main/examples/febrl)
/FebrlExample.py
without much luck. 

Has this been tried ? Is there an alternative to run zingg on a private cloud K8 cluster set up ? any lead would be appreciated.

**Comment by sonalgoyal** [comment]
This hasn't been tried as far as I know though I see no reason why it won't work as long as you are using the Zingg script to run the programs. Let us know how it goes and what errors you are getting.

**Comment by sonalgoyal** [comment]
Sorry it is hard to say.  Do your base java spark examples run fine?

**Comment by sonalgoyal** [comment]
Besides pyspark, you will need a running spark install

**Comment by sonalgoyal** [comment]
@pejathayaS - please let me know if you were able to solve this
