### ISSUE TITLE
Use environment variables in config files

### ISSUE THREAD

**Issue by jtinsky** [zinggAI/zingg#60]
I'm considering using Snowflake as my primary data store and I'd like to have the connection information stored as environment variables instead of strings in the config file as shown in the [Snowflake example config](https://docs.zingg.ai/docs/dataSourcesAndSinks/snowflake.html).

This was meant to be an enhancement/feature request so apologies if I submitted this incorrectly.

**Comment by sonalgoyal** [comment]
Thanks @jtinsky for this feature request! Can I please understand a bit more about the need for saving the values in env ? Is that for security? I assume you only need the data and the output attributes of the config to come from the env?

**Comment by jtinsky** [comment]
Yeah, for security reasons mainly. I want to store all the props as env
vars.

**Comment by sonalgoyal** [comment]
thanks @jtinsky , adding to zingg 0.4

**Comment by sonalgoyal** [comment]
We can build it like this - template each variable jsonAttr:{{env.VAR_NAME}} and pick up the VAR_NAME from system environment of the driver program.
