### ISSUE TITLE
Test obvious dupes 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#625]
- linker
- ftd
- performance on spark

**Comment by vikasgupta78** [comment]
Changes to be tested have been done as part of pull request #624

**Comment by sonalgoyal** [comment]
We see about half an hour in 3 hours end to end on Snowflake on 3m ish data and we dont have numbers for Spark yet. If there is a need for perf improvement, we can look at building a blocking tree from the match conditions and run a join
