### ISSUE TITLE
Add chosen records as candidate pairs to training data

### ISSUE THREAD

**Issue by jmcleod5** [zinggAI/zingg#634]
I am curious if I can add specific candidate pairs to training data. I would assume this could be done either by adding them to unmarked & marked candidate datasets in training data, or by pointing to a temporary pipeline table of only the candidate pairs in question and executing the findTrainingData step using a 100% sampling rate. 

Are there any caveats or built-in methods for adding specific pairs to training data?

**Comment by sonalgoyal** [comment]
Does this work for you?

https://docs.zingg.ai/zingg/stepbystep/createtrainingdata/addowntrainingdata

**Comment by jmcleod5** [comment]
Perfect, thanks!
