### ISSUE TITLE
log level change

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#649]
should be debug:
WARN zingg.common.core.executor.TrainingDataFinder - input data schema is StructType[StructField(ID, String, Nullable = true), StructField(FNAME, String, Nullable = true), StructField(LNAME, String, Nullable = true), StructField(STNO, String, Nullable = true), StructField(ADD1, String, Nullable = true), StructField(ADD2, String, Nullable = true), StructField(CITY, String, Nullable = true), StructField(STATE, String, Nullable = true), StructField(AREACODE, String, Nullable = true), StructField(DOB, String, Nullable = true), StructField(SSN, String, Nullable = true), StructField(Z_ZSOURCE, String, Nullable = true), StructField(Z_ZID, Long, Nullable = true)]

**Comment by sonalgoyal** [comment]
@vikasgupta78 ok to close?

**Comment by vikasgupta78** [comment]
PR #693 raised
