### ISSUE TITLE
Real time identity resolution

### ISSUE THREAD

**Issue by archenroot** [zinggAI/zingg#661]
Hello,

first thank you for this interesting work you have done with zingg. I did not install yet zingg, but would like to ask if you consider real time identity resolution with connectivity to either AWS MKS, Apache Kafka, Redis Streams or other messaging subsystems to inference incoming data against the existing customer profiles database?

Thank you for any hints/answers.

Kind regards,

Ladislav Zitka

**Comment by sonalgoyal** [comment]
thanks for exploring Zingg @archenroot. have you checked the link phase of Zingg which can match two datasets - one of them can be the existing one. you should be able to build the kafka dataset using https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html and then creating a df for batch processing and then using an InMemory Zingg Pipe 

I am afraid we dont have any published recipes for the same, so please do share how it goes and maybe we can do something together :-)
