### ISSUE TITLE
Could not find artifact com.wcohen.ss:secondstring:jar:2021 in Central Repository

### ISSUE THREAD

**Issue by archenroot** [zinggAI/zingg#662]
Tried to build zingg, but failed due artifact missing in repository
```
[ERROR] Failed to execute goal on project zingg-common-core: Could not resolve dependencies for project zingg:zingg-common-core:jar:0.3.5-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in Central Repository (https://repo1.maven.org/maven2/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project zingg-common-core: Could not resolve dependencies for project zingg:zingg-common-core:jar:0.3.5-SNAPSHOT: Could not find artifact com.wcohen.ss:secondstring:jar:2021 in Central Repository (https://repo1.maven.org/maven2/)
```

**To Reproduce**
1. run: `mvn clean compile package -Dspark=3.3 -X`

**Expected behavior**
process will create package

**Screenshots**
![image](https://github.com/zinggAI/zingg/assets/553512/d941a88d-a46d-418a-ab82-127f0bdb0f90)

I searched for the package, but wasn't able to find version **2021**
![image](https://github.com/zinggAI/zingg/assets/553512/633e4f3f-4bc8-41d5-8587-01c04dfef3d6)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu

**Comment by sonalgoyal** [comment]
please run mvn initialize

https://docs.zingg.ai/zingg/contributing/settingupzingg

**Comment by archenroot** [comment]
I added the library manually:
`mvn install:install-file -Dfile=thirdParty/lib/secondstring.jar -DgroupId=com.wcohen.ss -DartifactId=secondstring -Dversion=2021 -Dpackaging=jar -DgeneratePom=true`

Now it seems continue with build.
