### ISSUE TITLE
TrainingDataFinder preprocess issue

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#664]
TrainingDataFinder:
ZFrame<D,R,C> posSamplesOriginal = getPositiveSamples(data);
ZFrame<D,R,C> posSamples = getPreprocUtil().preprocess(args,posSamplesOriginal);
=> preproc should happen before getting positive sample   otherwise e.g. z_fname doesn't get preprocessed

(stopwords has been moved to preprocessor as part of issue #654 but this problem was existing earlier also with stop words)

**Comment by sonalgoyal** [comment]
Can you please explain what’s happening here?

**Comment by vikasgupta78** [comment]
when we do getPositiveSamples we do self join 
e.g. if df was like
z_zid fname 
now it would be 
z_zid fname z_z_zid z_fname

after that we do preprocessor based on fieldname which is fname
=> while stop words etc. get removed from fname but not from z_fname

we should be doing preprocessing/stop word removal before doing self join

**Comment by sonalgoyal** [comment]
thats a good find. Let us think through the preprocessing framework a bit more in that case.

**Comment by vikasgupta78** [comment]
I have gone thru the code of other executors and issue seems to be only in TrainingDataFinder
