### ISSUE TITLE
tabular python package installation gives error in  databricks

### ISSUE THREAD

**Issue by mohantaneja** [zinggAI/zingg#665]
**Describe the bug**
on installing tabular for DataBricks (based on this example notebook i.e.
https://github.com/zinggAI/zingg/blob/main/examples/databricks/FebrlExample.ipynb ) from PyPi
It gives an error:
ModuleNotFoundError: No module named 'distribute_setup'

**To Reproduce**
From DataBricks Cluster   
1. Compute --> Libraries  --> Install New --> Select PyPi
2. in the textbox type  -> tabular
3. Click install
  

**Expected behavior**
Should not give any error on install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: DataBricks on Azure
  - Browser: Edge 
 - Version (for DataBricks): 11.3x-scala2.12

**Smartphone (please complete the following information):**

**Additional context**
This should use some alternative library instead of tabular for this example since tabular has not been updated for more than a decade (based on PyPi)

**Comment by sonalgoyal** [comment]
@gnanaprakash-ravi can you please take @vikasgupta78's help to fix this in the 0.4.0 branch?

**Comment by gnanaprakash-ravi** [comment]
Sure, I will look into it

**Comment by sonalgoyal** [comment]
duplicate of #714
