### ISSUE TITLE
Databricks zinggLabler won't allow users to select the same value repeatedly

### ISSUE THREAD

**Issue by anth0ny-x** [zinggAI/zingg#667]
Hi,

The Databricks zinggLabler won't allow users to select the same value repeatedly. 

The line below, won't re-execute the cell if the values were unchanged.
https://github.com/zinggAI/zingg/blob/86f0635674539ae284bcb7cad0af5a989e58e437/examples/databricks/zinggLabeler.py#L108

**Comment by sonalgoyal** [comment]
I am afraid that’s a Databricks widgets limitation so we don’t have much control there. 😭
