### ISSUE TITLE
zingg.client.Arguments.setTrainingSamples() is not functioning as expected. 

### ISSUE THREAD

**Issue by jmcleod5** [zinggAI/zingg#669]
**Describe the bug**
When passing a pipe to the setTrainingSamples method of the Arguments class, I am getting `AttributeError: 'Arguments' object has no attribute 'setTrainingSamples'`, indicating an issue with class method. 

**To Reproduce**
`from zingg.client import *`
`args = Arguments()`
`(create csvPipe with name, location, schema, delimiter, and header info)`
`args.setTrainingSamples(<csvPipe name>)`
``
`>>AttributeError: 'Arguments' object has no attribute 'setTrainingSamples'`

**Expected behavior**
I expect the training samples to be added to the Arguments object and to be available for model training.

**Environment**
 - DBR v 10.4 LTS, Spark 3.2.1, Scala 2.12, Driver=Standard_E8_v3 64GB/8Core, Workers = same, max=6
 - Zingg 0.3.4 snapshot jar
 - Zingg python version: latest, pip installed in notebook

**Comment by sonalgoyal** [comment]
this functionality is not available in 0.3.4 yet. https://zingg.readthedocs.io/en/0.3.4/zingg.html#contents 

it will be there in the next release.
