### ISSUE TITLE
Most parts of the match operation in one thread

### ISSUE THREAD

**Issue by yrisob** [zinggAI/zingg#674]
Hi, there, I hope you are well.

Could you help us with the question, why is the main time of match operation executed in the one thread?
We detected that it's the operation:  count at ConnectedComponents.scala:311

As the interesting process of matching 200k records takes 30min and 28min it is executed in one thread.

**SPARK config**
spark.serializer                        org.apache.spark.serializer.KryoSerializer
spark.driver.memory                     61g
spark.driver.cores                      24
spark.executor.memory                   61g
spark.executor.instances                1
spark.executor.cores                    24
spark.kryoserializer.buffer.max         2047m
spark.executor.memoryOverhead           1g
spark.driver.memoryOverhead             1g
spark.memory.offHeap.enabled            false
spark.memory.offHeap.size               2g
#spark.akka.frameSize                   200
spark.rpc.message.maxSize               1024
spark.sql.autoBroadcastJoinThreshold    -1
spark.sql.debug.maxToStringFields       200
spark.jars                              /root/zingg/config/postgresql-42.6.0.jar
spark.driver.maxResultSize              16g
spark.python.worker.memory              16g
spark.python.worker.reuse               true
spark.scheduler.listenerbus.eventqueue.capacity=20000
spark.eventLog.enabled=true

**Comment by sonalgoyal** [comment]
This is an interesting observation, thanks for reporting @yrisob. How many records have you labeled and how many of those are matches?

**Comment by yrisob** [comment]
Hi, @sonalgoyal, thank you for your quick answer, we have those counts:
Labelled pairs so far    : 9/25 MATCH, 16/25 DO NOT MATCH, 0/25 NOT SURE

**Comment by yrisob** [comment]
@sonalgoyal, that is interesting, we increased the count of label values it solved our problem.  How many labeled pairs do you recommend to have
After we labeled these count of pairs. 18/61 MATCH, 29/61 DO NOT MATCH, 14/61 NOT SURE  it started used all cores.

**Comment by sonalgoyal** [comment]
Great! This is expected as the blocking model learns distribution through the labels you provide. Mostly our advice is to get to 30-40 matches and run match, then see performance and accuracy and train further if need be
