### ISSUE TITLE
zingg.common.client.Arguments.writeArgumentsToJSON does not exist in the JVM

### ISSUE THREAD

**Issue by gnanaprakash-ravi** [zinggAI/zingg#687]
in testArgs.py
while testing for writeArgumentsToJSON:
I am facing this error:
` .
======================================================================
ERROR: test_writeArgumentsToJSON (test.testFebrl.testArgs.ArgumentsTest.test_writeArgumentsToJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/r_gnanaprakash/zingg/test/testFebrl/testArgs.py", line 188, in test_writeArgumentsToJSON
    args.writeArgumentsToJSON(json_file_name)
  File "/home/r_gnanaprakash/miniconda3/lib/python3.11/site-packages/zingg/client.py", line 521, in writeArgumentsToJSON
    getJVM().zingg.common.client.Arguments.writeArgumentsToJSON(fileName, self.args)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spark-3.2.4-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1547, in __getattr__
    raise Py4JError(
py4j.protocol.Py4JError: zingg.common.client.Arguments.writeArgumentsToJSON does not exist in the JVM

----------------------------------------------------------------------
Ran 12 tests in 1677.094s

FAILED (errors=1)`

code used:
`def test_writeArgumentsToJSON(self):
        client = Zingg(args, options)
        client.initAndExecute()
        json_file_name = "arguments_file.json"

        args.writeArgumentsToJSON(json_file_name)

        self.assertTrue(os.path.exists(json_file_name))
        os.remove(json_file_name)
`

git log:
`(base) r_gnanaprakash@LAPTOP-51G8JQDT:~/zingg$ git branch
* 0.4.0
  main
(base) r_gnanaprakash@LAPTOP-51G8JQDT:~/zingg$ git log
commit 5517caa1d72ca6ef6dc4fa4a0b3817c78dd74f13 (HEAD -> 0.4.0, origin/0.4.0)
Author: gnanaprakash-ravi <gnana1306@gmail.com>
Date:   Mon Oct 9 18:37:49 2023 +0530

    UTs for Arguments class

commit 22f5c45a2415cf57cb570d54a933280613f84efd
Merge: 8eaaf10b 1ab905dc
Author: Sonal <sonalgoyal4@gmail.com>
Date:   Sun Oct 8 21:48:27 2023 +0530

    Merge pull request #681 from zinggAI/pipeutilchanges

    issue #680 Update python api for read and write arguments to json`

Please let me know if anything needs to be provided!!
Thank you

**Comment by vikasgupta78** [comment]
zingg.common.client.Arguments.writeArgumentsToJSON is no longer the code in latest client.py in 0.4.0.

Please tell the file name where you are seeing this code

**Comment by vikasgupta78** [comment]
Also have you done pip uninstall zingg and pip install . to get latest client.py code installed?

**Comment by gnanaprakash-ravi** [comment]
Thank you sir,
After doing pip uninstall zingg and pip install . in python dir, this issue is resolved!!
