### ISSUE TITLE
Support for linking three or more dataset

### ISSUE THREAD

**Issue by doku** [zinggAI/zingg#70]
Currently linking three datasets would require labeling and linking 2 pairs, one with the first pair and again with the result of the first pair and the third. This takes a lot of labeling time and setup to get working. Two config files would be needed using the same model and different phases order will be used. I think it would be prone to error. 

I think it would be more efficient if linking 3 or more datasets can be set up in the config file and labeled at once.

**Comment by sonalgoyal** [comment]
you should not have to label again. but the data in the config would need to be changed currently. labelling and training has to happen only when the column types and numbers change. 

Linking multiple one after the other internally is a good idea. So if you give multiple pipes in the data config, we can link across all of them in one go in the link phase.

**Comment by doku** [comment]
By the way, this is referring to this slack message. https://zinggai.slack.com/archives/C02JNH144TB/p1639040957042000?thread_ts=1638972378.041000&cid=C02JNH144TB

**Comment by sonalgoyal** [comment]
Labeling at once can be done by specifying all the three data files or more in the data attribute of the config. We will enhance the link phase to link one by one internally so that you do not have to do it externally. Does that help @doku?

**Comment by doku** [comment]
Yes thank you

**Comment by navinrathore** [comment]
The tests have been done for 3, 4 and existing 2 datasets LINK.
