### ISSUE TITLE
Issue in databricks notebook

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#714]
Tried to use https://github.com/zinggAI/zingg/blob/main/examples/databricks/FebrlExample.ipynb

While trying to use db notebook faced following issues:

1. pip install tabular => pip install tabulate
2. Need to add following before using Arguments:
from zingg.client import *
from zingg.pipes import *
3. getPandasDfFromDs => zingg.getPandasDfFromDs
4. writeLabelledOutputFromPandas missing

**Comment by sonalgoyal** [comment]
6dd343f4

**Comment by gs-syk** [comment]
@sonalgoyal - I just ran into the same issue with tabular; it looks like your commit to change the package to tabulate in the databricks example notebook may not have gone through because It's still showing tabular. Just thought I'd give a heads up!

**Comment by sonalgoyal** [comment]
thanks @gs-syk. The 0.4.0 branch https://github.com/zinggAI/zingg/blob/0.4.0/examples/databricks/FebrlExample.ipynb has this change, and this should get reflected in main branch once we release. Sorry for the cunfusion.

**Comment by sonalgoyal** [comment]
dbr 14.2 is the supported version for zingg 0.4.0
