### ISSUE TITLE
Connecting ZIngg AI to python and MSSQL server

### ISSUE THREAD

**Issue by ravinsanjula** [zinggAI/zingg#727]
Hi,
I have a few tables in the MSSQL database. I want to use Zingg to identify duplicates in those tables. Since I am familiar with Python I want to use Python to try out Zingg. could you give me the steps connecting to the MSSQL database and Zingg using Python?
And, How can I get the output table after identifying the duplicates?
Thank you

**Comment by sonalgoyal** [comment]
Here are the docs for using an RDBMS with Zingg. 
https://docs.zingg.ai/zingg/connectors/jdbc 

To use the data in Python, you can define a Pipe class and set its properties https://docs.zingg.ai/zingg/connectors/jdbc 

A complete example using csvs is at https://github.com/zinggAI/zingg/blob/main/examples/febrl/FebrlExample.py 

You can modify it for your use asper the first two docs

**Comment by ravinsanjula** [comment]
Thank you, Sonal,

could you explain what this code line is used for?
(from zingg.client import * )

**Comment by sonalgoyal** [comment]
It gets the Zingg python package - that’s a standard python import
