### ISSUE TITLE
Collect metrics can be passed as a command line argument as well, so you can add that to the arguments of ZinggWithSpark/Zingg python object just like the phase

### ISSUE THREAD

**Issue by jmcleod5** [zinggAI/zingg#748]
Reopening this topic in a new issue, I'm not able to get this working. 

```
from zingg.client import *
options = ClientOptions([ClientOptions.COLLECT_METRICS, "false"])

> AttributeError: type object 'ClientOptions' has no attribute 'COLLECT_METRICS'
```

Looking at the code base [here ](https://github.com/zinggAI/zingg/blob/0.3.4/client/src/main/java/zingg/client/ClientOptions.java), this appears to be the right syntax. The same syntax for setting `PHASE` works fine: 

```
from zingg.client import *
options = ClientOptions([ClientOptions.PHASE, "findTrainingData"])

> ['--phase', 'findTrainingData']
> arguments for client options are  ['--phase', 'findTrainingData', '--license', 'zinggLic.txt', '--email', 'zingg@zingg.ai', '--conf', 'dummyConf.json']
```

Any thoughts as to what the cause might be?

              Collect metrics can be passed as a command line argument as well, so you can add that to the arguments of ZinggWithSpark/Zingg python object just like the phase

_Originally posted by @sonalgoyal in https://github.com/zinggAI/zingg/issues/738#issuecomment-1846504423_

**Comment by sonalgoyal** [comment]
It seems that the Python API is not exposing the option through the variable. Can you try with 

`from zingg.client import *
options = ClientOptions([ClientOptions.PHASE, "findTrainingData"])
options.setOptionValue("collectMetrics", "False")`

**Comment by sonalgoyal** [comment]
also, I wanted to check regarding your requirements for the telemetry. We capture the metadata and Zingg runs to learn about usage patterns and adoption so that we can build effectively. Would love to know your concerns/feedback to make sure it doesnt harm your usage.

**Comment by jmcleod5** [comment]
It seems the `setOptionValue()` method is failing due to a lack of attribute `setValue`. 

This is the traceback: 
```
AttributeError                            Traceback (most recent call last)
<command-397889180866606> in <module>
     10 
     11 options = ClientOptions([ClientOptions.PHASE, "findTrainingData"])#.setOptionValue("collectMetrics", "False")
---> 12 options.setOptionValue("collectMetrics", "False")
     13 zingg = ZinggWithSpark(args, options)
     14 zingg.init()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-eebda7a9-7dd5-4c00-9b25-3b5646fadbcf/lib/python3.8/site-packages/zingg/client.py in setOptionValue(self, option, value)
    369         :type value: String
    370         """
--> 371         self.co.get(option).setValue(value)
    372 
    373     def getPhase(self):

AttributeError: 'NoneType' object has no attribute 'setValue'
```

Since this operation only needs to be performed once each time we execute, I am using the JSON r/w options as a workaround: 
1. After my existing on-the-fly config completes, I write the config to JSON
2. Open and edit the JSON w/ Python, saving back to disk
3. Load the JSON config back to Zingg w/ collectMetrics=False now in place. 

Regarding the use of telemetry, it's not that we have an issue with this as a general principal. However, we would need to verify the data being sent to ensure we meet regulatory requirements; a code review is not sufficient for our purposes. We don't have the capacity at present, so we are opting to turn off telemetry in the interim.

**Comment by sonalgoyal** [comment]
Sorry it did not work. looks like it only allows setting the preconfigured ones. 
Thanks for your views on the telemetry @jmcleod5. If we print out the data we are collecting, do you think that will help?

**Comment by sonalgoyal** [comment]
@jmcleod5 can you also check `options = ClientOptions([ClientOptions.PHASE,"your phase","--showConcise","true"])` and this can make it easier for you.

**Comment by sonalgoyal** [comment]
@gnanaprakash-ravi can you verify the fix I suggested above?

**Comment by gnanaprakash-ravi** [comment]
Hi,
Yes, I have verified this way of setting options is working.
`options = ClientOptions([ClientOptions.PHASE,"your phase","--collectMetrics","false"])`

Result:
```
24/02/28 16:24:47 INFO Client: *************************************************************************************************************
24/02/28 16:24:47 INFO Client: *    Zingg is not collecting any analytics data and will only log a blank event with the name of the phase  *
24/02/28 16:24:47 INFO Client: *************************************************************************************************************
```
