### ISSUE TITLE
python documentation html build loading spark 

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#762]
this makes readthedoc build fail 

`                        
sonal@sonal-mac docs % rm -rf _build/html; make html
Running Sphinx v7.2.6
path is 
/Users/sonal/zingg/python/zingg
making output directory... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
reading sources... 
looking for now-outdated files... none found
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] zingg
generating indices... genindex py-modindex done
24/01/04 10:34:38 WARN Utils: Your hostname, sonal-mac.local resolves to a loopback address: 127.0.0.1; using 192.168.1.40 instead (on interface en0)
24/01/04 10:34:38 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/01/04 10:34:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyspark/sql/context.py:113: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(
highlighting module code... [100%] zingg.pipes
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.`

**Comment by SemyonSinchenko** [comment]
I would like to try to fix it. May you assign it to me? Thank you!
