### ISSUE TITLE
set explicit spark version in dockerfile

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#77]
building new image pulls latest which may not be the spark version we have compiled against

**Comment by navinrathore** [comment]
The latest tag for bitnami supporting Spark 3.1 is 3.1.2 or 3.1.2-debian-10-r130. The same will be updated along with the new revision of zingg.

**Comment by navinrathore** [comment]
The Current image does not allow to update _SUCCESS file for findTraingData and Label
java.io.FileNotFoundException: /zingg-0.3.0-SNAPSHOT/models/101/trainingData/marked/_SUCCESS (Permission denied)

Need to revisit Read/Write permissions of the folder "models" and its contained files
