### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable on posit cluster

### ISSUE THREAD

**Issue by theimanph** [zinggAI/zingg#797]
Hi,

I installed the package an am going through the FebrlExample.ipynb. I am trying to use it on a posit cluster (not databricks). I am getting this error: TypeError: 'JavaPackage' object is not callable.. Any ideas on where the jar file is and/or how I can solve it? Thank you!!

Sincerely,

tom

**Comment by sonalgoyal** [comment]
The jar is available through the Zingg releases https://github.com/zinggAI/zingg/releases/tag/v0.4.0
