### ISSUE TITLE
Azure synapse compatibility

### ISSUE THREAD

**Issue by alrena68** [zinggAI/zingg#816]
I was trying to run zingg on Azure Synapse but when trying to invoke the zingg Client I get the error:

 "Py4JJavaError: An error occurred while calling o4095.execute.
: java.lang.NoSuchMethodError: 'org.apache.spark.sql.Encoder org.apache.spark.sql.Encoders.row(org.apache.spark.sql.types.StructType)' "

This seems to be caused due to the different spark version in Synapse (3.4) and the used spark version in zingg (3.5).

Is there still another way how to get zingg run in Azure Synapse with spark version (3.4) ?

**Comment by sonalgoyal** [comment]
Zingg 0.4.0 runs on spark 3.5.0. Is moving to the older Zingg release an option for you?
