### ISSUE TITLE
Is there a way to pre-train a brand new model?  e.g. `Jack == John`; `Joe-Bob == Alexander`; `id 123 == id 456`

### ISSUE THREAD

**Issue by knguyen1** [zinggAI/zingg#819]
We have thousands of potential duplicates in Salesforce, where people using alternative/anglicized names etc. is a big culprit.  For example, initial interaction can be off a resume where a person uses their nick name/anglicized name.  User inputs into the system that they talked to `David Kim`.  As they go further along the hiring workflow, they have to use their legal name.  So someone creates a new record for `Kim Sung-Uk`.  Lots of other anglisiz-ations are common.. like `Xiang -> Shelly`; `Baek -> Park`; `Zhang -> John`; `Kekoah -> Calvin`.

So let's say we pre-identified these possible duplicates.  Is there a way to feed Zingg this knowledge?

**Comment by sonalgoyal** [comment]
While zingg does provide the ability to plugin existing training data, lookups are not supported in the community version. For the open source version of Zingg, maybe you can look at doing some preprocessing of the data and having multiple variants.
