### ISSUE TITLE
Support for other feature types in non string fields

### ISSUE THREAD

**Issue by vikasgupta78** [zinggAI/zingg#821]
Support for other feature types in non string fields

Currently only fuzzy is there

**Comment by sonalgoyal** [comment]
we can add null_or_blank to integer, long and dates. other match types are not applicable. please also update docs https://docs.zingg.ai/zingg0.4.0/stepbystep/configuration/field-definitions

**Comment by vikasgupta78** [comment]
As discussed exact might have to be supported for numeric types

**Comment by vikasgupta78** [comment]
added null or blank and exact match type to int, long and date pr #824

**Comment by sonalgoyal** [comment]
@vikasgupta78 ok to close?
