### ISSUE TITLE
Merge Strategy in Zingg AI

### ISSUE THREAD

**Issue by prk2331** [zinggAI/zingg#826]
Zingg is providing the mechanism to resolve the customer identities, via z_score, z_indexes etc.
that out of 1000 customers, 300 are identical.   700 are unique records
**so is there any way in Zingg or any project in market that can do merging too on top of zingg, to the golden profile
like** 
custid customer_name   customer_interest  customer_dob  customer_blood_group      created_date
  2           John                         PlayingGames    1982-01-01         b-ve                              2002-01-02
  1           John                         Pets                    1982-01-01         b+ve                             2001-01-05

after resolving it to a single customer

want to apply merging on interest attribute of (KeepBoth),
want to apply merging on customer blood group attribute of (Value of current profile),
   Note: ValueOfCurrentProfile means the profile which needs to be consider as our master profile that profile contained value going to be persisted (For example: let's suppose somehow, we configured the app to consider greatest created_date as the golder profile 
   
custid customer_name        customer_interest             customer_dob     customer_blood_group    created_date
2           John                       PlayingGames, Pets           1982-01-01           b-ve                                    2002-01-02

**Comment by vikasgupta78** [comment]
Please check link option:

https://docs.zingg.ai/zingg/stepbystep/link

**Comment by sonalgoyal** [comment]
On the Zingg Enterprise product, we are building AI based survivorship. However, for the open source, a simplistic way of building the golden record is to process Zingg output through sql/pyspark and craft survivorship rules of your choice.
