### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable when calling args = Arguments()

### ISSUE THREAD

**Issue by jjconnolly85** [zinggAI/zingg#831]
Hi there, I get the following error TypeError: 'JavaPackage' object is not callable after importing as below: 
from zingg.client import Arguments, ClientOptions, ZinggWithSpark
and calling:
args = Arguments()

I am working in Azure Databricks runtime (ML 14.3)
I have installed Zingg successfully

detailed comment from error:
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936daaeb-54ce-4dc8-a407-c9283e2f74c6/lib/python3.10/site-packages/zingg/client.py:382, in Arguments.__init__(self)
    381 def __init__(self):
--> 382     self.args = getJVM().zingg.common.client.Arguments()

**Comment by sonalgoyal** [comment]
Zingg 0.4.0 needs dbr 14.2. 

Please also check that the correct version of the Zingg jar is available on the cluster

**Comment by jjconnolly85** [comment]
thank you so much, where do i get those requirements? They were not in docs :)

**Comment by sonalgoyal** [comment]
👍

This change was introduced by Databricks and we learnt about it much later. You can read more here https://semyonsinchenko.github.io/ssinchenko/post/how-databricks-14x-breaks-3dparty-compatibility/

We are rebuilding the api to support these changes

**Comment by jjconnolly85** [comment]
ok lovely support from you, thank you
