### ISSUE TITLE
Databricks Error - Py4JJavaError: An error occurred while calling o964.execute.

### ISSUE THREAD

**Issue by jjconnolly85** [zinggAI/zingg#832]
When I run this command:
options = ClientOptions([ClientOptions.PHASE,"findTrainingData"])
#Zingg execution for the given phase
zingg = ZinggWithSpark(args, options)
zingg.initAndExecute()

the job runs on azure databricks (14.2RT) for a long time but then fails with this error message:

java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply(Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/catalyst/encoders/ExpressionEncoder;

then this is the detail 
Py4JJavaError: An error occurred while calling o964.execute.

any help would be appreciated, thank you (I am so close now)

**Comment by sonalgoyal** [comment]
What’s the spark version of the dbr 14.2 RT? We need spark 3.5.0

**Comment by jjconnolly85** [comment]
14.2 (includes Apache Spark 3.5.0, Scala 2.12)

**Comment by sonalgoyal** [comment]
Can you please confirm that Zingg 0.4.0 jar only and not an older version
is available to the cluster?

Cheers,
Sonal
https://github.com/zinggAI/zingg

**Comment by jjconnolly85** [comment]
yes that is correct, that jar only 

zingg_0_4_0_SNAPSHOT.jar

**Comment by sonalgoyal** [comment]
i see. You have probably downloaded it from the Daatbricks notebooks which are pointing to the wrong prerelease jar. This code was removed from Zingg in 0.4.0 release. Can oyu please download from this repo releases directly and rerun? Thanks!

https://github.com/zinggAI/zingg/commit/768c40d2c964ebd8a5812d8a1a2c8992fbb1ab65#diff-87ed517f4c4f5e053a068730bd1be5de4f39c3efe16ffc999231e6925c7f65f8

**Comment by jjconnolly85** [comment]
yes the databricks documentation here is not the best...thank you for pointing me to the correct Jar file. could you advise please if i also need to %pip install zingg too? (slightly worried about any approach here right now)

**Comment by jjconnolly85** [comment]
thank you Sonal, I will report back to you :)
really appreciate the support - this thread will no doubt help the next databricks user

**Comment by jjconnolly85** [comment]
Hi Sonal, I am now getting the error below...
 
from zingg.client import *
from zingg.pipes import *

ModuleNotFoundError: No module named 'zingg.client'

**Comment by jjconnolly85** [comment]
thank you Sonal, I got this working. The code finally ran, thank you again

**Comment by sonalgoyal** [comment]
Cool, congrats!

**Comment by jjconnolly85** [comment]
@sonalgoyal thank you again. I wondered please do you have any notebook example where you create pairs across two separate dataframes please? Or one with the duds which do that? (Will speed me up no end). 
thanks again for the help
