### ISSUE TITLE
Pairs against two data frames

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#833]
@sonalgoyal thank you again. I wondered please do you have any notebook example where you create pairs across two separate dataframes please? Or one with the duds which do that? (Will speed me up no end). 
thanks again for the help

_Originally posted by @jjconnolly85 in https://github.com/zinggAI/zingg/issues/832#issuecomment-2113328998_

**Comment by sonalgoyal** [comment]
You can add multiple pipes to the data in arguments. 

use findTrainingData if you want to see diverse data while labelling.

use link if you want to match second against the first

**Comment by jjconnolly85** [comment]
ok thank you - do you have a notebook please which is doing this? so i can ensure i get it correct. thanks again
