### ISSUE TITLE
0 positive pairs when i had one

### ISSUE THREAD

**Issue by jjconnolly85** [zinggAI/zingg#834]
I am trying to save the response from the html findTrainingData sampling exercise, which identified one matching pair

but when i run the code to save samples as per this guidance: https://github.com/zinggAI/zingg/blob/main/examples/databricks/FebrlExample.ipynb

It is suggesting i have 0 positive matches:

You have accumulated 0 pairs labeled as positive matches.
You have accumulated 0 pairs labeled as not matches.
If you need more pairs to label, re-run the cell for 'findTrainingData'

help would be appreciated please Sonal :)

**Comment by vikasgupta78** [comment]
after running findTrainingData how many pairs were formed? Did you mark match, unmatch using the widget for all of them ? And after that did you run the subsequent code which saves?

**Comment by jjconnolly85** [comment]
Hi Vikas yes I did sir
It’s as if these responses aren’t being recorded through widget
Tried many times

**Comment by jjconnolly85** [comment]
Is it best to follow this process or the link above I shared as example?
as on reading this I didn’t get the same UI, I instead got three boxes to select. 

https://www.zingg.ai/documentation-article/identity-resolution-on-databricks-for-customer-360

**Comment by vikasgupta78** [comment]
I tried again and it worked fine for me using the notebook.

After selection from widget , box after "Save all the labels provided by the user" needs to be run to save it. I also checked with another customer and they are not having any issues with this notebook

I hope you are using databricks compute 14.2 with Spark 3.5

**Comment by sonalgoyal** [comment]
@jjconnolly85 are you using https://github.com/zinggAI/zingg/blob/main/examples/databricks/FebrlExample.ipynb modified? Can you share the image of the 3 boxes you are getting?

**Comment by jjconnolly85** [comment]
![image](https://github.com/zinggAI/zingg/assets/35108534/791a552a-a052-45f9-b2e3-8462de702686)

hi @sonalgoyal  thank you here is image and yes using that link modified.

**Comment by sonalgoyal** [comment]
Thanks. Are you clicking on the buttons to say match no match and then running the save cell in the notebook?

**Comment by jjconnolly85** [comment]
hey yes that is exactly it - when you say save cell you mean this command, right?
![image](https://github.com/zinggAI/zingg/assets/35108534/c70b61ef-e179-4684-a039-b0cb2ad30550)

**Comment by sonalgoyal** [comment]
Yes. Make sure you go over all the records and click one of the buttons(match/not match/unsure) for each record and then click save

The records in the gif you sent appear in one single line. Our code displays each column in a separate line and then the buttons. Please make sure your data is being read correctly.

One way could be to try the example as it is and then run your stuff so you can compare

**Comment by jjconnolly85** [comment]
I just re-ran this and had same issue - with one match it flagged 0 when saving. Could you please check this code Sonal quickly?
https://github.com/zinggAI/zingg/blob/main/examples/databricks/FebrlExample.ipynb
from the above? As there was a subtle issue i think with the indent of pair_id = (this line was not indented, so I amended slightly - the only thing i have done differently)

how it appears on link above:
# extract candidate pair id from html pair content
    start = pair.children[0].value.find('data-title="')
    if start > 0: 
      start += len('data-title="') 
      end = pair.children[0].value.find('"', start+2)
    pair_id = pair.children[0].value[start:end]

how it appears in my code:
 # extract candidate pair id from html pair content
    start = pair.children[0].value.find('data-title="')
    if start > 0: 
      start += len('data-title="') 
      end = pair.children[0].value.find('"', start+2)
      pair_id = pair.children[0].value[start:end]

**Comment by jjconnolly85** [comment]
I have just amended the above to match exact format in the /FebrlExample.ipynb
but this is saying 
No labels have been assigned. Run the previous cell to create candidate pairs and assign labels to them before re-running this cell.

I note that this above example is an ipynb (jupyter notebook), it is not a databricks DBC? Would it be possible to arrange a call with you for 30 mins please to show you my issue? What i then would offer is a complete Databricks example which is working. 

@vikasgupta78  is your client you checked with using Databricks? I am using correct runtime etc

**Comment by vikasgupta78** [comment]
Yes client is using Databricks and imported the notebook via URL into the workspace

**Comment by sonalgoyal** [comment]
sure feel free to grab a spot, lets try to get this to work!

**Comment by jjconnolly85** [comment]
thank you so much Sonal, you are such a help. It would be great to meet you and i promise not to take up too much time. I am testing this on a specific region at present, but want to roll it out across our enterprise (once i have fully learned / applied e2e. 

thank you - what is you emails address please?

**Comment by sonalgoyal** [comment]
happy to help and excited to meet you! https://calendly.com/sonalgoyal/30min?month=2024-05

**Comment by jjconnolly85** [comment]
hi @sonalgoyal  hope you are ok and thank you for supporting on this. I wanted to let you know that I tested ipywidgets and they worked ok here:
![image](https://github.com/zinggAI/zingg/assets/35108534/92ed5ac6-583f-4e9d-9a49-25df2414e60d)

**Comment by sonalgoyal** [comment]
what happens when you run the febrl example notebook as is? do you see the widget rendering properly?

**Comment by jjconnolly85** [comment]
I am running it as it is...nothing differently has been done my side other than use our data. could you or @vikasgupta78  ask the other client for their databricks cluster configs exactly perhaps please? thank you again

**Comment by sonalgoyal** [comment]
We have this working at other places with the cluster specs you have. What happens when you run the febrl example with no changes? Do you see the widget pop up correctly?

**Comment by sonalgoyal** [comment]
how is this going @jjconnolly85 ?

**Comment by AppyKul** [comment]
Hi @sonalgoyal ..
I am also facing the same issue where the counts are displayed as 0. 
Is there any explicit Save button after labelling the data?

**Comment by sonalgoyal** [comment]
duplicate #842
