### ISSUE TITLE
Are ipywidgets supported in Databricks community edition? 

### ISSUE THREAD

**Issue by AppyKul** [zinggAI/zingg#841]
Hi,

I am trying to run the commands in FebrlExample.ipynb . But the command with ipymb widgets runs and just says 
 Loading...

I am using DBR 14.2 

Please advise on how to proceed with this.

**Comment by vikasgupta78** [comment]
Can you please give more details around the version of spark being used, version of zingg being used and screenshot of error you are seeing?

**Comment by AppyKul** [comment]
Spark version used is 3.5.0

Does the Databricks Community version supports these widgets?

Screenshot attached below:

![Capture](https://github.com/zinggAI/zingg/assets/173446995/7d43d802-6bff-447a-90a9-77105b4fa4a2)

**Comment by AppyKul** [comment]
Zingg version is 0.4.0

**Comment by vikasgupta78** [comment]
Databricks community version comes with limited features so it's quite possible but I think best to check that with databricks as this doesn't seem to be an issues with Zingg.

**Comment by AppyKul** [comment]
Yes , I have posted  a query on DataBricks Community as well. Have not received an answer yet.

**Comment by sonalgoyal** [comment]
did this work or do you need help here @AppyKul ?
