### ISSUE TITLE
Incremental Documentation not formatted properly

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#843]
https://docs.zingg.ai/zingg0.4.0/stepbystep/runincremental

**Comment by sonalgoyal** [comment]
https://docs.zingg.ai/zingg0.4.0/stepbystep/configuration/deterministicmatching as well

**Comment by sonalgoyal** [comment]
wording - please check  around already 
"Zingg Enterprise allows the ability to plug rule based deterministic matching along with already Zingg AI's probabilistic matching"

Also, these pages should have their header as Deterministic Matching - *Zingg Enterprise Only

**Comment by sonalgoyal** [comment]
also add * to the enterprise features on the nav

**Comment by vikasgupta78** [comment]
Doc update:

From: Kyle Bowerman <[kyle@atrium.ai](mailto:kyle@atrium.ai)>
Sent: Monday, July 1, 2024 9:12 PM
To: Sonal Goyal <[Sonal@zingg.ai](mailto:Sonal@zingg.ai)>
Subject: deterministic question
 
Sonal, thank you for answering the customer questions Friday.   I have another question about the deterministic match.  In the example below.  I don't understand how this is used.   Are we saying that the first match condition is  and AND as that we are group three sets of field and they all have to be true:   fname, stNo, and Add1 in order for it to be a match and contribute to the z_min, z_max score?   and I have three sets of these so are these like an OR condition?

I asked on the call if we can weight fields in the z_score and you said no, I understand this is not weighting the score but is rather making composite matches.   How does this example with with three matchCondtions?

Thanks
Kyle


"deterministicMatching":[
    {
       "matchCondition":[{"fieldName":"fname"},{"fieldName":"stNo"},{"fieldName":"add1"}]
    },
    {
       "matchCondition":[{"fieldName":"fname"},{"fieldName":"dob"},{"fieldName":"ssn"}]
    },
    {
       "matchCondition":[{"fieldName":"fname"},{"fieldName":"email"}]
    }
]
