### ISSUE TITLE
facing issue while running Databricks 360 entity resolution example

### ISSUE THREAD

**Issue by prk2331** [zinggAI/zingg#865]
Team
   im getting connection errror, below is the screenshot 
<img width="878" alt="image" src="https://github.com/user-attachments/assets/6d18af4c-9244-4625-b60f-ca2680839dbf">

  below is the screenshot of zingg class
  
<img width="785" alt="image" src="https://github.com/user-attachments/assets/6c9a3ab7-9371-471d-952c-5abfe262ce24">

  please guide, where the change is required to work this
  
  Best regards,
  Puneet

**Comment by prk2331** [comment]
@sonalgoyal can you please guide.

**Comment by sonalgoyal** [comment]
Can you please try Zingg with Python on Databricks? There is a febrl notebook under examples Databricks that you can refer to
