### ISSUE TITLE
FAQs on Zingg

### ISSUE THREAD

**Issue by prk2331** [zinggAI/zingg#867]
1. Is running Zingg on newly upcoming incremental data (to maintain the same "z_cluster" of new similar records) is an enterprise feature?
2. Deterministic matching is also an enterprise feature?
3. How do I mark the profile as a golden/primary profile against all of its similar profiles?

@vikasgupta78  @sonalgoyal    can you please help me in my above queries..

Thanks

**Comment by sonalgoyal** [comment]
Yes incremental and deterministic are enterprise features.

You can run a sql script in pyspark over Zingg results to build a golden profile

**Comment by prk2331** [comment]
@sonalgoyal thanks for your response
what are the pricing models for this enterprise features?

"You can run a sql script in pyspark over Zingg results to build a golden profile"
so to do this manual code is required . Right ?

And what about merging of data into the golden/primary master profile? Assume one similar profile contains "Pets" as an interest, and another similar profile's interest is "Finance."? and we want to put both of them, "Pets" and "Finance," into the golden profile.

**Comment by sonalgoyal** [comment]
Merging Zingg matches into a golden record is a manual step for now. You can use sql defined functions for an outcome of your choice, or write a custom program.

Pricing can be discussed separately

**Comment by prk2331** [comment]
hi @sonalgoyal ,  sorry to open it again.
but I want to ask one more question in this thread.
In the model's folder, there are 7 folders.
100 101 102 103 104 105 106 9999
and in this demo
[https://www.youtube.com/watch?v=zOabyZxN9b0&t=631s](https://www.youtube.com/watch?v=zOabyZxN9b0&t=631s)
we are using 
**"modelId": 100**
Q1. when to use other models, is this all are same?
and 
"labelDataSampleSize" : 0.5
Q2. I want to run the same example on my dataset where I have 3,84,000 rows, what "labelDataSampleSize" need to mention there?

Thanks
