### ISSUE TITLE
FAQs on zingg

### ISSUE THREAD

**Issue by prk2331** [zinggAI/zingg#868]
@sonalgoyal 
I want to ask one more question in this thread. Please guide
In the model's folder, there are 7 folders.
100 101 102 103 104 105 106 9999
and in this demo
https://www.youtube.com/watch?v=zOabyZxN9b0&t=631s
we are using
"modelId": 100
Q1. when to use other models, is this all are same?
and
"labelDataSampleSize" : 0.5
Q2. I want to run the same example on my dataset where I have 3,84,000 rows, what "labelDataSampleSize" need to mention there?

Thanks

**Comment by vikasgupta78** [comment]
is the dataset on which you are trying to run having same schema as the example model?

**Comment by prk2331** [comment]
@vikasgupta78  Thanks for your reply.
No, we need to change the config. json accordingly (data is different)
I pushed my CV inside the Docker container, and now I'm trying to run this same example with my data.
is there any chance of conflicts (if we run same model on our other data )?

**Comment by vikasgupta78** [comment]
If your schema is different the existing models will not work, you will have to train your own model

**Comment by prk2331** [comment]
hi @vikasgupta78 
is this link is useful to train our own model for our another data set ?
[https://docs.zingg.ai/zingg0.3.3/stepbystep/createtrainingdata/addowntrainingdata](https://docs.zingg.ai/zingg0.3.3/stepbystep/createtrainingdata/addowntrainingdata)

**Comment by prk2331** [comment]
Any medium blog or video link
for a better understanding of how to create our own model ?
