### ISSUE TITLE
Unable to see files and formats supported on Databricks 

### ISSUE THREAD

**Issue by sania-16** [zinggAI/zingg#879]
<img width="1204" alt="Screenshot 2024-08-09 at 11 31 33 AM" src="https://github.com/user-attachments/assets/13d89c41-9193-4100-bc6c-4a294fac7820">

**Comment by sania-16** [comment]
where can I find the missing info to update this?

**Comment by sonalgoyal** [comment]
this file doesnt seem to be needed. you can check docs.zingg.ai and if anything is broken, fix that directly. safe to remove this file to avoid confusion.
